yalesites-org/yalesites-project

.gitignore, .lando.local.example.yml, .lando.upstream.yml, README.md
- Creates a lando config file for all sites using the upstream. This uses the Pantheon recipe to leverage supporing commands such to sync Pantheon environments with the local dev.
- Includes an example local lando file to help developers set site specific environmental variables.
- Adds the local lando file to gitignore
- Includes minimal changes to the README as a future ticket includes deeper contribution instructions.
```
name: yalesites4kupstreamtest16
config:
id: ed6c6a92-74fe-46f2-9bc5-b500b2ecc0b7
site: yalesites4kupstreamtest16
```
=> YALB-256: Setup Lando

web/profiles/custom/yalesites_profile/config/sync/block.block.alert_block.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pop_out_image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.image_float.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.pop_out_image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.media.image_float.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.full_width.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_float.yml, web/sites/theming.services.yml
- https://github.com/yalesites-org/component-library-twig/pull/80
- https://github.com/yalesites-org/atomic/pull/7
- Creates a`theming.services.yml` file that disables basically every cache so that theming is easier (must be opted in via `settings.local.php` - so it won't affect developers not actively working on the theme)
- Places the `alert_block` ... somehow that got missed before?
- Creates a "Full Width" responsive image style and applies it to the default view mode for the image media type
- Creates a "Image - Float" responsive image style and applies it to the "Image - Float" view mode for the image media type
- Configures the "Pop-out Image" to render its image using the "Image - Float" view mode
=> YALB-521: Wire Pop-out Image

composer.json
- Some users are running into an issue running `lando start` due to the default 300s composer timeout. I thought it might be an issue on older machines but I just experienced it on a 2018 Macbook Pro. This change increases composer process-timeout to to 600s.
```
187/189 [===========================>]  98%    Install of drupal/core failed
Install of yalesites-org/atomic failed
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details
[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "'/usr/bin/unzip' -qq '/app/vendor/composer/tmp-32ef6aef09a09ce508c461277acbe341' -d '/app/vendor/composer/e4758c8e'" exceeded the timeout of 300 seconds.
```
=> fix: increase process-timeout for composer

web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/README.md, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/layouts/two-column/ys-layouts--yds-twocol.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.info.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.layouts.yml, web/profiles/custom/yalesites_profile/yalesites_profile.info.yml
- Defines a new ys_layouts module to contain custom layouts for the platform.
- Creates a new layout for a two column layout and provides a template for this layout.
- Enables the ys_layout module. Also enables contextual links. Not important for this PR, be we will leave it in there for now unless there are any objections.
=> YALB-525: Two Column Layout Builder Layout

scripts/local/rebuild.sh, scripts/local/setup.sh, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
- Wires the Image paragraph type
=> YALB-476: Wire Image Paragraph

.lando.local.example.yml, composer.json
- Moved the composer process-timeout override to `.lando.local.example.yml`
- Increased the value from 600s to 1800s
I was continuing to have issues building a local environment on an older Macbook Pro with the `composer install` step timing out. Increasing the timeout to 1800s fixed it but I also found that the config can be overridden in the landofile, so I moved it out of composer.json. Now, it won't get set on Pantheon.
- Run `npm run setup` and confirm there are no composer process timeout errors
=> refactor: move composer timeout to landofile from composer.json

composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/editoria11y.settings.yml
- Adds and configs Editoria11y module.
=> YALB-519 - adds Editoria11y module

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.banner_16_5.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.preview.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.image.preview.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.pop_out_image.preview.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.text.preview.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.media.banner_16_5.yml, web/profiles/custom/yalesites_profile/config/sync/crop.type.banner_16_5.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1120.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1280.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1440.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1600.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1760.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1920.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2080.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2240.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2400.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_320.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_480.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_640.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_800.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_960.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.banner_16_5_.yml
- Creates a "Banner (16:5)" crop type
- Creates "Banner (16:5)" image styles and responsive image style
- Creates "Banner (16:5)" media view mode, and configure it to use the above
- Updates the Banner component to use the above media view mode
- Tweaks some of the preview view modes of paragraphs
=> YALB-527: Image Cropping

web/profiles/custom/yalesites_profile/config/sync/system.action.user_add_role_action.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.user_add_role_action.site_admin.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.user_remove_role_action.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.user_remove_role_action.site_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
- Adds site_admin and platform_admin user roles
- Adds default permissions for each role
=> YALB-451: BE: Roles and Permissions

web/profiles/custom/yalesites_profile/config/sync/layout_paragraphs.modal_settings.yml
- Fixes modal resizing by configures modal settings
=> YALB-536: configs layout_paragraphs modal

scripts/local/setup.sh
- `composer.lock` was not being written to `.git/info/excludes` when running `npm run setup`. It looks like we just need to reverse the condition.
=> fix: reverse condition on composer.lock check

web/profiles/custom/yalesites_profile/config/sync/node.type.news.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml
- Adds content type descriptions for news and page
=> chore(YALB-567): add news and page content type descriptions

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
- Adds teaser image on page
- Updates the teaser media field to use the media library widget
=> YALB-551: update teaser media widget.

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.preview.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_heading.yml
- Adds heading field to cta banner
- updates the cta banner paragraph field so the page <title> is no longer used as the CTA banner heading.
=> fix(YALB-606): adds heading field to cta banner.

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/devel.settings.yml, web/profiles/custom/yalesites_profile/config/sync/devel.toolbar.settings.yml, web/profiles/custom/yalesites_profile/config/sync/system.menu.devel.yml
- Install and configure Devel and Devel Kint Extras
You can also put this in your `settings.local.php` if kint takes too long/too much memory (you can adjust the depth to whatever works for you. 3-5 seems to be a pretty good range)
```
/*
* Set Kint's max_depth to prevent memory issues.
*/
if (class_exists('Kint')) {
Kint::$max_depth = 5;
}
```
=> Install and enable devel and devel_kint_extras

composer.json, web/profiles/custom/yalesites_profile/composer.json
- Moves the ys_cas module to packagist to avoid unnecessary github token. This is already a public repo.
=> YALB-444: Remove github token step for setup

web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_banner.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_heading.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml
- Allows pages to be added to the utility navigation.
=> YALB-254: Allows pages to utility nav

web/profiles/custom/yalesites_profile/config/sync/views.view.event_cards.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.news_cards.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.news_list.yml
- Updates the news and events views to support passing the heading from the paragraph down to the view
=> YALB-610: Wire Pager

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_actions.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_tasks.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.breadcrumbs_2.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml, web/profiles/custom/yalesites_profile/config/sync/menu_breadcrumb.settings.yml
- Adds menu breadcrumb module
- Breadcrumbs will follow menu structure, not path structure
=> YALB-614: Follow menu trail

docs/development.md, scripts/local/rebuild.sh, scripts/local/setup.sh, web/profiles/custom/yalesites_profile/config/sync/block.block.social_links_block.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/YSCoreFooterSettingsForm.php
- Updates the template to follow the shape defined in the component library (icon, name, url)
- Moves common work to a custom service
- Renames social links config to make it easier to use this namespace for other projects
- Invalidates the cache on form submit
I messed up and committed most of this work directly to develop. I forgot this was not a protected branch for this project and this caused most of my commits to go right to dev. For code review please use the following compare:
- [What changed in this work](https://github.com/yalesites-org/yalesites-project/compare/25ee0ed46ff92525c8fca993c124d913269c16af..5c933325da7b596135f791353334289eb7237ecd)
=> YALB-612: Refactor social links

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-breadcrumb-block.html.twig
- Adds ```is_active``` to each breadcrumb item to denote if it is the active page
=> YALB-635: Add is_active to breadcrumb items to denote active page

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
- Prepend home link to the breadcrumb list
=> YALB-667 - Prepend home to breadcrumb list

web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml, web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.site_specific_ignored_config.yml, web/profiles/custom/yalesites_profile/config/sync/ys_core.social_links.yml
- Removed ```ys_core.*``` from config ignore settings
- Creates a new config split for site specific config and adds ```ys_core.*``` so all ys_core settings are ignored when performing drush cex/cim
=> feat(YALB-328): Ignore site specific config settings

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.image_content_width.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.media.image_content_width.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.full_width.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_content_width.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_max_width.yml
- Add responsive image style for content width image
- Change title of Full Width image style to Image - Max Width to match Storybook
- Change default image style for image paragraph to use new content width image
=> YALB-665: Add responsive image style for content width

web/profiles/custom/yalesites_profile/config/sync/system.site.yml, web/profiles/custom/yalesites_profile/config/sync/ys_alert.settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraph_callout.json, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraphs.json
- Changes demo content with feedback from tickets: YALB-641, YALB-643, YALB-644, and YALB-645
=> YALB-288: Demo Content Updates

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.event_cards.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.news_cards.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.news_list.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Changes wording of core "sticky" field from "Sticky at top of lists" to "Pin to the beginning of list" for node add forms.
- Note: This does not affect the back-end wording for use in views, etc. Those areas will still say "Sticky at top of lists".
- Adds checkbox for "Pin to beginning of list" to events edit page. The News edit page already had this field enabled.
- Changes views sort order for the four views (two each for news and events) to sort first by "sticky" and then by the previously enabled date field.
=> YALB-41: Promoted news/events items

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/override_node_options.settings.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Requires and enables the override_node_options module
- Sets permissions for site admins to edit news node 'authored on' date
- Removes the 'promote' option from the manage news form (as we do not need it).
- Fixes warning by checking if sticky form element isset.
=> YALB-590: News: Change publication date

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
- Updates machine color names to match component library
=> YALB-691: Update machine color names to match component library

.ci/deploy/pantheon/dev-multidev
Sometimes during CI deployments, the build fails on the `drush updatedb` step because the environment has not finished spinning up, and the database is not yet reachable.
```
Notice: ] Command: ***.pr-71 -- drush updatedb [Exit: 137]
Error: ]  SQLSTATE[HY000] [2002] Connection refused 
SQLSTATE[HY000] [2002] Connection refused
Error: Process completed with exit code 1.
```
This started from a Slack thread: https://pantheon-community.slack.com/archives/C57J1MUEM/p1660148365952049
It appears to be an intermittent issue with others using Pantheon Build Tools, so I have proposed this change to the templates project as well: https://github.com/pantheon-systems/tbt-ci-templates/pull/17
=> YALB-687: DevOps: fix intermittent failed CI builds

web/profiles/custom/yalesites_profile/config/sync/ys_themes.theme_settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Adds cssvars to the page :root
- Updates cssvars based on the global theme settings stored in Drupal
- Exports a copy of the global theme settings configuration. While this is config ignored, we need a starter place for when new sites are installed.
- This work is procedural and does not include error handling, testing, or other backend goodness. A 'todo' was added to refactor this code once the frontend architecture/naming convention is established. A lot of decisions need to be made and keeping everything in one function makes for a more readable place to experiment.
```css
:root {
--color-theme-button-primary: var(--color-blue-yale);
--color-theme-pull-quote-accent: var(--color-gray-500);
--color-divider: var(--color-gray-500);
}
```
=> YALB-684: Theme Settings: Generate CSS variables

web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Allows for accordion items to have a dynamic heading level based on the parent accordion heading
- Adds a variable available in ```paragraph--accordion-item.html.twig``` called ```has_outer_heading```
- Logic for what heading level it should be will be placed in ```paragraph--accordion-item.html.twig```
```
{% include "@molecules/accordion/_accordion-item.twig" with {
accordion__item__heading: content.field_heading,
accordion__item__content: content.field_content,
accordion__item__heading__level: has_outer_heading ? 3 : 2
} %}
```
=> YALB 502: Dynamic heading levels

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Adds quick links style variation to links field to correctly style links
=> YALB-719: Quick links style variation for link field

web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml, web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.site_specific_ignored_config.yml, web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.events.yml, web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.news.yml, web/profiles/custom/yalesites_profile/config/sync/ys_core.site.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.tokens.inc
- Defines a new config for for ys_core settings.
- Adds settings for news and events landing page paths.
- Reorganizes validation the site settings form.
- Creates custom tokens for the new landing page paths.
- Sets up path auto patterns for news and events leveraging these paths.
- Enables the config split as it was disabled.
=> YALB-681: News/Events: Base path setting and token

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Check if the parent paragraph exists before calling the `has` method. This currently fails when creating new accordion item paragraphs as the parent does not exist until the node is saved.
=> YALB-729: Bug: Creating accordion items

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemesTwigExtension.php
- Adds an additional twig function to get all theme settings in an array
=> YALB-286: Add ability to get all theme settings in twig

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.media_grid.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.media_grid_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.media_grid.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.media_grid_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_content.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.media_grid.field_heading.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.media_grid.field_media_grid_items.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.media_grid_item.field_media.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_media.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_media_grid_items.yml, web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.media_grid.yml, web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.media_grid_item.yml
- creates image grid and image grid item paragraph type for news/events/pages.
=> YALB-708: creates image grid and image grid item paragraphs type

web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_content.yml
- Changes accordion item content cardinality to 1.
- Removes the ‘Add Text’ button that appears in the paragraph modal.
=> YALB-295: Set accordion item cardinality

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.media_library.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.media_library.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_media_file.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_media_file.yml, web/profiles/custom/yalesites_profile/config/sync/media.type.document.yml
- Adds the 'document' media type according to the data model.
- Exports all related configuration
- Reference: [Data Model](https://yaleedu.sharepoint.com/:x:/r/sites/YaleSitesUpgradeProgram/_layouts/15/Doc.aspx?sourcedoc=%7B2B574C06-BAC3-41E2-924A-F4562054F849%7D&file=Proposed%20Content%20Model.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-ELECTRON.teams.files&wdExp=TEAMS-CONTROL&wdhostclicktime=1644421397192&cid=d943a478-b42a-4c48-81f5-277a615700d1)
=> YALB-281: Document: Create media type

web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_actions.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_tasks.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_messages.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.exposedformsearchpage_1.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.main_page_content.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.pagetitle.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.yalesitesbreadcrumbs.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml, web/profiles/custom/yalesites_profile/config/sync/search_api.server.database_server.yml, web/profiles/custom/yalesites_profile/config/sync/views.settings.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.search.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Adds a search form to the utility navigation area
- Adds a search form to the search view
- Enables additional search processors
- Adds a dynamic meta title to the search page if there are search terms
- Adds number of results to the search view
- NOTE: This requires [PR-46](https://github.com/yalesites-org/atomic/pull/46) from atomic and [PR-147](https://github.com/yalesites-org/component-library-twig/pull/147) from component-library-twig
=> YALB-700: Search Form and Settings

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.event.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.news.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml, web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
- Allows content authors to exclude specific nodes from search
=> YALB-703: Search: Opt out of index

web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/ys_starterkit.install
- Removes install hook that won't do anything for this project. This works to initiate migrations on module install, but not profile install
- Keeps the uninstall hook so if the module is uninstalled, the correct configs are removed
=> YALB-736: Feedback: Remove starterkit install hooks

web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.page.yml
- Defines a pathauto pattern for all pages based on menu hierarchy.
=> YALB-732: Pages: Url Alias defaults

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
- Fixes bug where content that was not in a menu was showing the breadcrumbs. No breadcrumbs should show for non-menu items
=> YALB-717: Bug: Breadcrumbs for content without a menu link

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
- Hides unhelpful media form fields.
- Adds "Hide revision field" module
=> YALB-271: hides media form fields

composer.json, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/quick_node_clone.settings.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Story: As a content owner, I do not want to manually recreate content. I want to avoid the chore of copying and pasting. Examples: a series of events that have closely related content. I want to recreate a layout and will use the clone module as a starting place.
- The Quick Node Clone module is required via composer and install via Drupal Config management.  
- Site Admins can clone any node (page, event, or news).
=> YALB-518: AX: Ability to clone nodes

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Fixes error message ```Notice: Trying to access array offset on value of type null in ys_core_preprocess_region() (line 47 of profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module).```
=> YALB-702: Fix error message for show/hide search config

web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_link.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraphs.json
- Makes the link field for the action banner required.
=> YALB-766: action banner button

web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.permissions.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.routing.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.permissions.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.routing.yml
- Defines permissions in the ys_core and ys_alerts modules
- Apply this permission to the YaleSites settings forms
- Add the permission to site admins and platform admins
=> YALB-74: Add permissions for yalesites settings forms

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.media_library.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.media_library.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.accordion_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_cards.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.embed.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_cards.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_list.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.media_grid.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_cards.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_list.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pull_quote.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tab.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.video.default.yml
- Updates the set max length text fields for paragraphs in drupal.
=> YALB-752: set max lengths in drupal

.ci/build/build_frontend, .ci/deploy/pantheon/dev-multidev, .github/workflows/build_deploy_and_test.yml, .gitignore
Builds are currently failing on the build_frontend step when files being modified are managed by Composer.
This PR updates the build_frontend script to build out the atomic theme dependencies and remove the dependency from composer so that Integrated Composer running on Pantheon does not conflict. This is accomplished by introducing the cut line to `.gitignore`, modifying some of the ignored theme paths, and running `terminus build:gitignore:cut` so that `/web/themes/contrib/atomic/` can be committed when running in CI.
This also fixes an a second issue issue that caused builds to fail around the same time, for another reason: https://github.com/actions/runner/issues/2033
=> YALB-762: Bug: Fix CI build - multidev not created

composer.json
- Removes extra unnecessary "remove" button from paragraphs that have cardinality of 1 and the field is required.
- Note: The patch for this was added to the root composer file. If this needs to go into the profile composer file, let me know and I will move it.
Before patch:
After patch:
=> YALB-283: AX: Remove confusing remove-button

web/profiles/custom/yalesites_profile/config/sync/node.type.event.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.news.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml
- Disables preview option for content types.
=> YALB-628: disables preview for content types

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.user.user.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.menu.static_menu_link_overrides.yml, web/profiles/custom/yalesites_profile/config/sync/system.date.yml, web/profiles/custom/yalesites_profile/config/sync/system.site.yml, web/profiles/custom/yalesites_profile/config/sync/views.settings.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.files.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_news.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml, web/profiles/custom/yalesites_profile/config/sync/ys_core.site.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.action.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.tokens.inc
- Creates a views page for pages, news, and events.
=> YALB-485: creates views for pages, news, and events

.github/workflows/build_deploy_and_test.yml, composer.json, web/profiles/custom/yalesites_profile/composer.json
Adds a CI check to make sure root composer.json require array only contains drupal/core*.
=> YALB-793: CI: check for module additions to root composer.json

scripts/local/local-cl-dev.sh
- Updates the local cl dev script to patch Twig.js
=> Fix local cl dev script

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraphs.json
- Allows platform admins to edit the pull quote text and the heading and subheading fields for the text with image on content generated from the starterkit
- Fixes the error when attempting to visit the Footer Settings page
- Note: Reimport of the starterkit migration is required, steps below
=> YALB-809: Bug Feedback: limited permissions on fields for Platform Admins

.ci/deploy/pantheon/dev-multidev, web/profiles/custom/yalesites_profile/config/sync/system.site.yml
- Runs config import on multidev creation
=> YALB-790: DevOps: Run cim on multidevs

web/profiles/custom/yalesites_profile/config/sync/block.block.yalesitesbreadcrumbs.yml
- updating templates to render the breadcrumb block instead of drupal block layout
- review with https://github.com/yalesites-org/atomic/pull/59
=> YALB-405: Feedback: Breadcrumbs

composer.json, web/profiles/custom/yalesites_profile/composer.json
- Moves patches from the root composer.json file to the yalesites_profile composer.json
=> YALB-774: TechDebt: Move patch to the profile

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.default.yml
- Updates the news content type to use ‘Layout Paragraph’ formatter/widget on the main content field.
=> YALB-785: enables layout paragraphs for news

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/smart_date.smart_date_format.html_datetime.yml
- Allows all day events to use the string "All Day" in place of the time.
- Display uses "smart date formatter"
- Requires PR: https://github.com/yalesites-org/atomic/pull/58
- Requires PR: https://github.com/yalesites-org/component-library-twig/pull/160
=> YALB-757: all day events

web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_actions.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_tasks.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_messages.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.exposedformsearchpage_1.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.main_page_content.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.pagetitle.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.yalesitesbreadcrumbs.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
**Depends on https://github.com/yalesites-org/atomic/pull/65**
- Disables LPB on the frontend
- Moves system blocks into the "system" region
=> YALB-830: Disable layout paragraphs FE experience

README.md, package.json, scripts/local/local-theme-link.sh
- Adds `local-theme-link` script to run all the same set up commands as the `local-cl-dev` but meant to only be run once and _does not_ include `npm run develop` at the end. 
- After running `npm run local:theme-link` once, you can use npm run local:cl-dev` for developement
- Should we simplify the `local-cl-dev` script to only run the following?: 
```
cd _yale-packages/component-library-twig || exit
echo -e "${GREEN}Run the develop script in the component library${ENDCOLOR}"
npm run develop
```
Or would that require adjusting other scripts and/or is there a reason not to simplify?
=> Add local theme link script

composer.json
- Adds drupal console to the project as a composer dependency.
=> YALB-845: Add Drupal Console

web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
- Remove beige as a color option from the callout styles
=> YALB-841: Remove color from callout

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.wrapped_image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.wrapped_image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.wrapped_image.preview.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.wrapped_image.field_style_position.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.wrapped_image.field_style_variation.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
- Adds two new style overrides to the wrapped image component
- Organize style fields in a separate horizontal tab to match other paragraphs
=> YALB-815: Add wrapped image overrides

web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
- Updates Text with Image paragraph fields and overrides them.
=> YALB-112: overrides text with image paragraph fields

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.default.yml
-  Hide teaser and metadata fields from default node displays.
=> YALB-821: Hide teaser fields

web/profiles/custom/yalesites_profile/config/sync/block.block.claro_help.yml, web/profiles/custom/yalesites_profile/config/sync/block.block.help.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.event.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.news.yml, web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml
- Enables the help module
- Place the help block on the admin theme
- Adds node instructions to each content type
=> YALB-570: Node help text

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
- Removes duplicate content when using sections
- Internal notes: This changes the field formatter widget from "Referenced Entity" to "Layout Paragraphs" but does not use the "Layout Paragraphs Builder" as we had previously, so there are still no controls for editing content on the front-end. I have verified that the markup between "Referenced Entity" and "Layout Paragraphs" is the same but the duplicated content is removed with the latter.
=> YALB-857: Feedback: Section component content duplicates on the page

.ci/deploy/pantheon/dev-multidev, .ci/test/static/run, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_mail/README.md, web/profiles/custom/yalesites_profile/modules/custom/ys_mail/src/Config/MailConfigOverrides.php, web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.info.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.module, web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.services.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/README.md, web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/src/Config/SecretsConfigOverridesBase.php, web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/src/SecretsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/ys_secrets.info.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/ys_secrets.services.yml
- Refactors the ys_mail module to move secrets management code to a separate module
- Enables the new ys_secrets module
- Defines a method for disabling and adding a description to overridden fields in Drupal
- Add instructions for adding secrets in the new readme file.
=> YALB-912: Secrets Management

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_tags.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.news.field_tags.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_tags.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_tags.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.tags.yml
- Adds tags vocabulary
- Adds taxonomy term reference field to Page, News, and Event content types
- Sets the widget settings and placement of the fields for the form
- Removes the tag field from the display
=> YALB-936: Views: Tagging content

package.json, web/profiles/custom/yalesites_profile/config/sync/ys_alert.settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_alert/js/confirm_type_modal.js, web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/AlertManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Form/AlertSettings.php, web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.libraries.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.services.yml
- Adds alert types to the config yaml files
- Creates a management service for retrieving content from the config files
- Refactors the 'Alerts Settings' form type field to use a radio button and to pull text from the configuration yaml files.
- Adds a Drupal dialog in JS to provide a confirmation message before creating an emergency alert.
=> YALB-861: Alerts UI

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/ViewsBasicFilter.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-formatter-preview.html.twig
- Adds the ability to filter views basic lists by a taxonomy term in the tags vocabulary
- At the moment only one term is supported and help text is added to inform the content editor
- There is some work in Drupal core over single value autocomplete widgets not warning about cardinality: https://www.drupal.org/project/drupal/issues/2951134 so for the moment, if there are multiple values, the last value is used.
=> YALB-937: Views: Filter by tag

web/profiles/custom/yalesites_profile/config/sync/cas_attributes.settings.yml
CAS users who have been given a role but are not in the Yalesites Grouper group are stripped of that role on their next login because of the CAS Attributes setting "Remove role from user if match fails?". This changes the value to false to stop this from happening.
=> Bug: roles are removed from users if not part of Grouper group

.github/workflows/build_deploy_and_test.yml
- Tracking the [upstream version](https://github.com/pantheon-systems/tbt-ci-templates/blob/main/d9/providers/githubactions/.ci/.github/workflows/build_deploy_and_test.yml) of `.github/workflows/build_deploy_and_test.yml`, update to PHP 8.1 version of build tools project in CI.
=> YALB-952: Update CI Build Tools to PHP 8.1

web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.routing.yml
- Adds permissions for each user type (no functional change here, just feels good to check the boxes)
- Updates the callback for the embed entity modal to grant authors permission to view the content
=> YALB-969: Add media permissions

web/themes/custom/ys_admin_theme/ys_admin_theme.theme
- Changes the node edit form title to have the format: `<em>{{content type}}:</em> {{node title}}`
=> YALB-932: Node edit form title

web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.callout_item.field_link.yml
- Makes callout link text required.
=> YALB-941: Bug: Callout should require link text

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_content_title.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.news.field_content_title.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content_title.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_content_title.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/node-edit-form.js, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module, web/themes/custom/ys_admin_theme/css/admin-ui.css, web/themes/custom/ys_admin_theme/css/admin-ui.css.map, web/themes/custom/ys_admin_theme/scss/admin-ui.scss
- Moves teaser fields to the sidebar
- Placeholder text for teaser title is dynamically updated from the node title
- "Banner" renamed to "Intro Banner"
- Added "Page Content" H2 title inside the "Content" tab at the top
=> YALB-852: AX: Build follow up to fieldgroups work

web/profiles/custom/yalesites_profile/config/sync/metatag.settings.yml
- Removes advanced metatags from node edit forms
=> YALB-902: AX: Hide "Advanced" metadata tab

web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/src/EventSubscriber/NodeAccessEventSubscriber.php
- Fixes caching issue when reverting a CAS required page to not require CAS login, cache will no longer redirect viewing of node
=> YALB-651: Bugfix for CAS-restricted nodes

web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-formatter-preview.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
- Adds sorting ability to the Views Basic interface.
- For now, the options are: Published Date (News), Event Date (Events), and Titles (Pages) with both ASC and DESC orders for each. Each sort label, field, and orders can and will be changed after Yale feedback.
Views Basic allows content editors to select some criteria to show lists of other content as you would normally do via the Views interface, but with a more controlled and limited interface. For now, the content type of "Pages" is a placeholder as we intend to replace pages with people profiles. Therefore, the Pages sort is an example of how we can change the context of the sort from date-based sorts (for News and Events) to text-based sorts.
=> YALB-1010: Views Sorting

web/themes/custom/ys_admin_theme/css/admin-ui.css, web/themes/custom/ys_admin_theme/css/admin-ui.css.map, web/themes/custom/ys_admin_theme/scss/admin-ui.scss
- Update styles to fix position of items when hover on local task
=> YALB-1012: Admin Theme: Local Tasks style

web/profiles/custom/yalesites_profile/composer.json
- Fixes Link patching issue
- At version 6.0 dev branch
- Removes patch as this is now in the dev branch
=> YALB-1044: Feedback: Error installing Linkit Patch

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.basic_view.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.basic_view.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.basic_view.preview.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.basic_view.field_heading.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.basic_view.field_vb_params.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/node-edit-form.js, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-formatter-preview.html.twig
- Adds views heading field
- Reworks layout of widget to match mockup (see attached)
- Refactors some code from the default formatter into the manager for reusability
- Adds count of results to the preview so content authors know how many results before saving
- This ticket will not cover theming, that will be a separate ticket.
- The mockup shows an "Options" section that handles how many items and paging. As per a Teams conversation with Yale, it was agreed that since Views core handles paging in a certain way, we should mimic that same behavior. The second screenshot shows this reworked options area where the "Number of items to display" is a drop down, and when "Display all items" is selected, the limiter field will be hidden. Otherwise, the limit field will be shown and the label …
=> YALB-1006: Create views builder widget

.github/workflows/build_deploy_and_test.yml
Pin node version to 16.13 in CI to fix broken frontend build step.
=> ci: pin node version to fix frontend build step

README.md, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_float.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
- [YALB-1055 - Alignment: Text to Left Edge and Text to Right Edge](https://yaleits.atlassian.net/browse/YALB-1055)
- Components now have a left alignment with a limited inner width so text doesn't run too long while aligning along the left-hand rail. 
- [YALB-1056 - Alignment: Menus ](https://yaleits.atlassian.net/browse/YALB-1056)
- the primary menu top item text should now properly align with the site name, and do so whether left or right aligned
- [YALB-1065 - Alignment: Wire changes to Drupal](https://yaleits.atlassian.net/browse/YALB-1065)
- [YALB-1023 - Feedback: Consistant grid across components](https://yaleits.atlassian.net/browse/YALB-1023)
- We reviewed the wrapped image and text spotlight components during a working group session. From this meeting we agreed to remove the …
=> fix(yalb-alignment): increase wrapped image width

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
- Adds layout builder restrictions and layout builder restrictions per role modules
- Enables modules
- Patches layout builder restrictions by role to allow user 1 to add any block
- Note: No restrictions are put in place by this PR as there were none defined in the data model. Therefore, functional testing steps will review how to add a restriction by role and test it
- Multidev here: https://pr-242-yalesites-platform.pantheonsite.io/
=> YALB-1083: Content Model: Restrict blocks by role

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
- Adds menu items under "Content" menu to manage the main and utility navigation menus
=> YALB-1043: Nav: Allow authors to use manage menu UI

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/views.view.media.yml
- Patches the gin_lb module to fix an issue where the file upload field is missing. See https://www.drupal.org/project/gin_lb/issues/3349745 
- Also includes a configuration change to enable the media library views so that site admins can see this interface.
- These changes are made as a hotfix to the master branch so that we can release the changes without pushing levers and dials forward. All changes will be backported to develop once approved.
=> (hotfix) YALB-1140: File upload field is missing

web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
- Updates a layout browser setting to use the modal version. This resolves a current issue with the block search form.
=> YALB-1113: Enable modal layout browser

web/profiles/custom/yalesites_profile/config/sync/views.view.frontpage.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.layouts.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/ys-themes.css, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Adds theming for admin pages that need to be centered and to have a max-width applied
- Adds a template to Atomic here: https://github.com/yalesites-org/atomic/pull/116
---
---
---
---
=> YALB-1091 - Style admin forms that appear in atomic

.lando.local.example.yml, docs/xdebug.md
- Add lando configuration commands to enable/disable xdebug sessions
- Ensure xdebug is off by default
- Add documentation of usage
- .lando.local.example.yml:  I was unsure where else this was used.  If pantheon uses this in some way, this could affect usage there.
- twig file debugging: I was able to get this working in Neovim/nvim-dap by executing devel_breakpoint() inside the twig file, which flowed to the PHP scripts that were executing the echo-ing of the output.  This did not work, however, inside of Visual Studio Code.  It may be easier to recommend utilizing Kint/dump instead for consistency?
- I did not link to the new document to any specific place; I was not sure which was appropriate, on the main README or inside one of the existing documents.
=> YALB-261: Local Dev Setup Xdebug

scripts/local/local-review-with-cl-branch.sh, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.divider.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.divider.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_position.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_width.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
NOTE: [Atomic](https://github.com/yalesites-org/atomic/pull/120) and CL (merged) PRs must also be present (Same Branch Names)
- Adds YaleSites configuration updates that allow divider to have width and position dials
- Displays the divider in Drupal while respecting width and position dial settings
- Fix `local-review-with-cl` to copy from the _yale-packages folder after build
=> YALB-1137: Dividers add new dials to divider block

web/profiles/custom/yalesites_profile/composer.json
- Applies a patch to close the block modal after adding the block to the page.
- See https://www.drupal.org/project/layout_builder_browser/issues/3352754
=> YALB-855: Close modal after adding block

web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php
- On the admin toolbar, when viewing a node, update the toolbar links:
- Rename ‘Edit’ → ‘Setup’
- Rename ‘Layout’ → 'Layout Builder'
=> YALB-1183: Update labels on toolbar

web/profiles/custom/yalesites_profile/composer.json
- Removes patch that has now been incorporated not the latest version of the hide revision field module.
- Fixes an error during `composer install` where this patch could not be applied.
=> Hide revision field patch cleanup

web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.module
- Add ys_alert preprocessor hook to add a cache dependency such that updating invalidates rendered cache
=> fix(YALB-1123): Cache invalidated on alert save

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml
- Sets the "Teaser Text" field to have a maximum length of 150 characters, on all content types.
- Sets the "Teaser Text" field to have a hard limit for all content types.
=> YALB-457: sets max-length for teaser text fields

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.token.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/metatag.metatag_defaults.global.yml, web/profiles/custom/yalesites_profile/config/sync/metatag.metatag_defaults.node.yml, web/profiles/custom/yalesites_profile/config/sync/metatag.metatag_defaults.node__post.yml, web/profiles/custom/yalesites_profile/config/sync/metatag.settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.tokens.inc
- Adds a new token to get the teaser title if set, but if not, fallback to the node title.
- Enables and configures Open Graph metadata globally and also for articles
=> YALB-814: Metatags Open Graph (SB/BE)

web/profiles/custom/yalesites_profile/modules/custom/ys_alert/css/ys_alert.css
- Fixes a bug on the alert form so the current selected option has a blue border and a darker border when using the keyboard tab.
=> YALB-1190: Fixes alert setting select bug

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.wrapped_image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery_item.default.yml
Update the maxlength character limits for the following media text fields:
- Wrapped Image captions: 150 chars hard limit
- Video descriptions: 200 chars soft limit
- Image (standalone) captions: 200 chars soft limit
- Gallery Image Caption: 200 chars soft limit
- For each of the listed block types, verify the lengths and limit types. Links are provided below for each:
=> YALB-892: Media: Update Character Limits (SB)

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
- Installs and enables the calendar_link modules for the Atomic PR of the same name to function
=> YALB-1195: Events: Add to Calendar Link (BE)

web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/images.json
- Adds additional images into the content on install
- Changes location of original images for new versioning directory structure on S3
=> YALB-1199: Media: Organize media on install (BE)

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quick_links.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/css/ys_toolbar.theme.css
- Replace the autocomplete widget with the native link control
- Add a vendor prefix to the CSS to display the Yale logo in the corner
=> [Hotfix] YALB-1246: Replace linkit widget with native link control

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
- Updates allowed view modes on views basic to `card` or `list_item` to match other content types.
=> YALB-609: Page lists and grid display modes

composer.json, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/google_analytics.settings.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.authenticated.yml, web/profiles/custom/yalesites_profile/config/sync/ys_core.site.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
- Add and enable the google_analytics
- Updates the config-ignore list so that sites can have unique GA property IDs
- Adds a Google Analytics ID field to the site settings form, including validation.
```html
<script async src="https://www.googletagmanager.com/gtag/js?id=G-12345678"></script>
```
=> YALB-340: Google Analytics

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.view.field_view_params.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.taxonomy_lookup.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/ExcludeTaxonomyTerms.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
- Includes work from [PR 276 for YALB-1198](https://github.com/yalesites-org/yalesites-project/pull/276) as a starting point
- Adds the ability to exclude terms in a view
- Reworks how terms are chosen on the view settings form: there are two fields, one for including terms, and the other for excluding terms.
- When including terms, the "Any (OR) /All (AND)" operator works as expected
- When excluding terms, this will ignore the "Any/All" operator and instead default to "Any (OR)" as otherwise things get very confusing very quickly. We can change this if we want to add another "operator" control to control just the exclude in addition to the include.
- Adds an entity reference view to help when choosing terms for the two reference fields above. This new view simply adds the vocabulary …
=> YALB-1211: Exclude a term in views

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.user.user.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_event_type.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_category.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_event_type.yml, web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_posts.yml, web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_terms.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_format.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_type.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.post_category.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/config/install/migrate_plus.migration.ys_terms.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/terms.json
- Creates a new 'post category' vocabulary and adds it to the post content type.
- Creates a new 'event type' vocabulary and adds it to the event content type.
- Deletes the existing 'event format' field.
- Defines a migration of starterkit terms for post category, event category, and event type.
- Sets permissions so that site admins can manage all vocabularies except event type.
=> YALB-1231: Create and populate categories

.gitignore, package.json, scripts/local/local-cl-dev.sh, scripts/local/local-git-checkout.sh, scripts/local/local-review-with-atomic-branch.sh, scripts/local/local-review-with-cl-branch.sh, scripts/local/local-theme-link.sh, scripts/local/util/say.sh
- Includes [YALB-715](https://yaleits.atlassian.net/jira/software/projects/YALB/boards/368?selectedIssue=YALB-715) as it's closely related
- Script prepends script name to any output so you can know what is running (useful later when other scripts attempt to use this one)
- New script `local-git-checkout.sh` that can safely change branches on any of the 3 repositories (`token`, `component-library-twig`, and `atomic`)
- Create symlinks to each repo at the base directory to quickly get to the development versions (gitignored)
- Give error messages should the script error, such as directories not existing
- Clears Drupal cache if the `atomic` branch is changed
- Other scripts utilize new `say` utility method to help readability: i.e. `local-cl-dev.sh`
- It will not switch repos if there are …
=> YALB-971: LocalDev theme setup scripts

scripts/local/local-git-checkout.sh
fix(YALB-971): force composer for atomic
When setting up a yalesites project, composer does not use the name 'origin', but instead uses a remote name of 'composer'.  This caused some issues when attepmting to switch branches on atomic, as there would be two tracking branches, and it didn't know which to take.  This now passes the 'composer' remote only for atomic and passes it through.
- Fix script to allow the `composer` remote for atomic only
- YaleSites repo defaults to `develop` if branch doesn't exist
=> YALB-971: LocalDev: Theme setup scripts fix

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.view.field_view_params.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/EventTimePeriod.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
- Adds the ability to filter events in the views tool to show only future events, only past events, or all events.
- Forces all views to only show published nodes.
=> YALB-1239: Filter to show past events

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/bugherd.settings.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.anonymous.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.authenticated.yml
- Adds and configures Bugherd module with Yalesites Upgrade Project ID
- Applies [patch](https://www.drupal.org/project/bugherd/issues/3364305) to allow anonymous users to fill in the email field when it is required
:warning: Disable any ad blocking extensions in your browser (Adblock Plus, uBlock Origin, etc)
=> YALB-1294: Install and configure Bugherd module for testing

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.event_category.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.post_category.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.tags.default.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_category.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_type.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.post_category.yml, web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.tags.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/taxonomy-form.css, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Adds menu items to manage taxonomy vocabularies for site-admins
- Adds vocabulary descriptions to the overview page as well as individual vocabulary management pages.
- Removes unnecessary fields from taxonomy term edit pages.
=> YALB-1212: Enable taxonomy interfaces for authors

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.install
- Updates grand hero components that were created previous to variation and position key changes.
- Changes `reduced` to `contained` for grand hero positioning.
- Changes `contained` to `reduced` for grand hero variation.
=> YALB-1022: Bug: Grand Hero Design Option labels flipped

web/profiles/custom/yalesites_profile/composer.json
- Removes the patch for Gin Layout Builder that adds a media upload button because it has been included in the latest version of Gin Layout Builder.
- Fixes local composer build errors
=> Remove media library upload button patch for Gin LB

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/src/EventSubscriber/NodeAccessEventSubscriber.php, web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.module
- [YALB-1033: Bug: Unpublished items in menu (BE)](https://yaleits.atlassian.net/browse/YALB-1033)
- [YALB-1298: Bug: Unpublished content in search (BE)](https://yaleits.atlassian.net/browse/YALB-1298)
- Fixes unpublished items from showing in search and in menu items - these items will no longer show in these places if unpublished.
=> YALB-1033, YALB-1298: Unpublished Content

scripts/local/local-review-with-atomic-branch.sh, scripts/local/local-review-with-cl-branch.sh
While creating `say.sh`, I forgot to source the proper location of it in the local review scripts, resulting in error messages when attempting to write messages through the say command.  This now references correctly, as well as checking for the file so we can know when there is a problem.
- Replace execution of `./util/say.sh` to `source ./scripts/local/util/say.sh`
- Add guard clause check so if say.sh moves or is removed in the future, we know it's not loaded.
=> YALB-1333: Source correct location of say.sh

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
…hange
- Fixes a bug when changing the Navigation Type in the theme settings panel and saving the settings, the menu would not change until the cache was cleared. Now, when changing the Navigation Type and saving the settings, the change is immediate.
=> YALB-1313: Bug: Menu levers not updating website (BE)

web/profiles/custom/yalesites_profile/config/sync/views.view.search.yml
- Fixes bug where no results text wasn't showing properly.
- No results text will now show if search terms are entered and no results are found.
- New search text will now show if no search terms are entered. (i.e. on `/search` with no keywords query parameter)
- Requires [Atomic PR-136](https://github.com/yalesites-org/atomic/pull/136)
=> YALB-1288: Bug: Search no results message (BE)

web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Form/AlertSettings.php
* [YALB-1304: Bug: Alert char limits (BE)](https://yaleits.atlassian.net/browse/YALB-1304)
* [YALB-1344: Feedback: Alert settings the link fields are flipped order](https://yaleits.atlassian.net/browse/YALB-1344)
- Adds 255 hard character limit to alert description
- Swaps link text and link URL fields to match established order elsewhere on the site
- Changes alert copy for enabling alert
=> YALB-1304, YALB-1344: Alert Settings Bugs

web/profiles/custom/yalesites_profile/config/sync/block_content.type.pull_quote.yml, web/profiles/custom/yalesites_profile/config/sync/block_content.type.text.yml, web/profiles/custom/yalesites_profile/config/sync/bugherd.settings.yml
- Changes the bugherd module setting to move the button to the left side of the screen for submitting feedback.
- Adds revisioning to missing blocks. This is pure tech debt and has no functional or testable change on the site.
=> YALB-1136: Move bugherd button to the left

web/profiles/custom/yalesites_profile/composer.json
- Prevents adding more media items to a limited media item field
- Requires [Atomic PR-139](https://github.com/yalesites-org/atomic/pull/139)
=> YALB-1318: Bug: media library - gallery block - multiple photos error

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.media_grid_item.default.yml
- Changes media grid image view_mode from `default` to `card_secondary_3_2` to match the gallery component's view_mode
=> YALB-1363 - Bug: Media Grid images are different sizes on the main page

web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.post.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.post_cards.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.post_list.yml
- Changes post sorting for cards and lists to use "Publish Date" field instead of creation date.
- Also has an Atomic piece in [PR-142](https://github.com/yalesites-org/atomic/pull/142) that changes the visual display of the post date (in cards, lists, and default node view) from the creation date to the date in the "Publish Date" field.
=> YALB-1295: Bug: Posts display date of creation and not Publish Date

web/profiles/custom/yalesites_profile/config/sync/block.block.ys_admin_theme_local_tasks.yml, web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php, web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/ys_toolbar.module
- Updates toolbar labels as described in the test plan below
- Adds an upbulish button to all published nodes.
- Hide these secondary tasks block on node forms in the admin theme
=> YALB-1411/1412/1329: Update toolbar labels, add unpublish button

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.button_link.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.grand_hero.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.quick_links.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.callout_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.default.yml
- Disabled the 'truncation' settings for links fields for the following instances:
- Block "Button Link", link field
- Block "Content Spotlight", link field
- Block "Action Banner", link field
- Block "Grand Hero", link field
- Block "Custom Cards", in the "Custom Card" paragraph, link field
- Block "Callouts", in the "Callout Item" paragraph, link field
=> YALB-1450: Link field truncates and breaks long links

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
- Adds a linkit field widget to site settings form for picking the site home page.
=> YALB-597: Enable linkit for homepage setting

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.custom_cards.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.gallery.default.yml
- Update entity reference widgets to use button variation. This applies to the 'custom card' and 'gallery' blocks. We want to use the same controls as other blocks.
For reference, this controls originally looked like this on two of the block types:
But are now simply a button:
=> YALB-1256: Consistant 'add' label for reference fields

web/profiles/custom/yalesites_profile/config/sync/field.field.media.background_video.field_media_video_file.yml
- Increase background video size from 5MB to 12MB.
=> YALB-1434: Increate max video size

web/profiles/custom/yalesites_profile/config/sync/filter.format.heading_html.yml
- Title is misleading. Another issue on this ticket was brought up by Ashley: "Text CTAs are also too close to the text (in action banners)."
- Heading HTML text format will no longer strip out `<p>` tags
- Fixes the issue with the text being too close to the CTA in action banners
- Tested all other components and all looked fine except for
- Quote component attribution broke - we need to address this in the component library CSS is my guess
=> YALB-1290: Bug: Grand Hero Text alignment

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_teaser_media.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_teaser_text.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_teaser_title.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_teaser_media.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_teaser_text.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_teaser_title.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_teaser_media.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_teaser_text.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_teaser_title.yml, web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml
- Adds description text to teaser fields (title, text, and media) for Pages, Posts, and Events
=> YALB-309: Metadata: Teaser instruction and help text (UX/SB)

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml, web/profiles/custom/yalesites_profile/config/sync/linkit.linkit_profile.default.yml
- Enables autocomplete tools for Drupal to create links to files within the CKEditor link tool.
=> YALB-1208: Link to documents in WYSIWYG links

web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml
- Add a config change to set `classic_toolbar: horizontal` instead of `vertical`
- Makes the secondary toolbar `position: fixed` and sets the `top` property equal to the height of the primary toolbar. 
- Adds the height of the secondary toolbar to the `body.gin--horizontal-toolbar` styles so that the secondary toolbar pushes the content down and doesn't cover up the header or an alert.
https://github.com/yalesites-org/yalesites-project/assets/366413/b7df0e0b-37dc-4618-a56a-88eddc05efc7
=> YALB-1419 - OPAC: Move admin toolbar to top

web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_175.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_540.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.max_width_444.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.max_width_540.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.banner_16_5_.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_featured_3_2.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_list_3_2.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_secondary_3_2.yml, web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.text_with_image_feature_equal.yml
- CTA Banners = :purple_circle: - minor change added to PR
- Grand Hero = :heavy_check_mark:  (no changes needed)
- Image  / Content Image = :heavy_check_mark:  (no changes needed)
- Content Spotlight = :purple_circle: - minor change added to PR
- Custom Cards & Media Grid / 3:2 card secondary = :purple_circle: - minor change added to PR
- Views - Posts - List/Grid  3:2 card list = :purple_circle: - minor change added to PR
- Card List Featured | Responsive image style = :red_circle:  - minor change added to PR - However, this style is not currently in use. 
https://github.com/yalesites-org/yalesites-project/assets/366413/c8e10380-542d-4119-b1cc-91dbb0d15c25
https://github.com/yalesites-org/yalesites-project/assets/366413/0e56c28f-51e5-4387-b5d7-ceb3f1702ff8
=> YALB-1297: Media: Verify images are using optimized styles

web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesTitleBreadcrumbBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-title-breadcrumb.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Add a 'page_title__display' variable to the page title to switch the display between: 'display', 'hidden', or 'visually-hidden'.
- Display: renders the same code as before without a perceivable change.
- Hidden: No longer renders the page title block.
- Visually Hidden: Adds the class to the block to visually hide using preexisting styles.
- Sets these three options as configuration on the Title/Breadcrumbs block for pages
=> YALB-1135: Allow titles to be visually hidden

composer.json
- Drush 10 is no longer supported. This issue upgrades Drush to 11 to fix issues with `migrate:import --group` no longer working from migrate_tools, since it has deprecated support for Drush 10: https://www.drupal.org/project/migrate_tools/issues/3373882
=> YALB-1452: Bug: StarterKit Migrations failed: Update Drush

composer.json, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/chosen.settings.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_category.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_tags.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_tags.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_category.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_tags.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/themes/custom/ys_admin_theme/css/gin-custom.css
- Add Chosen module
- Add composer-merge-plugin to handle jjj/chosenjs dependency through composer
- Change Page, Post, and Event tag entry to use chosen
- Change Event category to use chosen
- Change View block's include/exclude fields to use chosen
- Change listing of include/exclude fields to be sorted by name for easy traversal
- Changed chosen dropdown colors to provide proper contrast for accessibility
- Updated help text associated with content types to convey that they cannot add items
=> YALB-1233: Improved term picker with ChosenJS

.ci/deploy/pantheon/dev-multidev
- Replaces individual `updatedb`, `config:import`, `cache-rebuild` drush commands with single [`deploy`](https://www.drush.org/12.x/deploycommand/) command
=> YALB-1465: Switch CI scripts to use drush `deploy`

web/profiles/custom/yalesites_profile/config/sync/cas.settings.yml, web/profiles/custom/yalesites_profile/config/sync/cas_attributes.settings.yml
- When a user is added manually as a CAS user, a dummy email address is required to create the account. This was supposed to be updated with the user's real email address from a CAS Attribute after login, but is not working. This adds an additional configuration to use the mail CAS Attribute.
- Also adds `noreply.yale.edu` as the default email hostname when creating a new user manually, so end users don't need to fill it in. The email on the user account gets updated from CAS Attributes on the user's next CAS login.
=> Bug: CAS user email addresses not being updated on login

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
- Adds checks to variables to prevent errors in logs when view is loaded in other ways (node indexing, for example)
- Fixes issue with taxonomy terms not filtering correctly on views after upgrading from Drupal autocomplete to Chosen library
=> Views basic fixes

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
- Add and enable [Search API HTML Element Filter extension](https://www.drupal.org/project/search_api_html_element_filter)
- Add `.visually-hidden` as a selector to remove before indexing
- Enable `Tokenizer` and `HTML Filter`
NOTE: I ran it here, but existing sites will need to re-index for it to take the new processors.  Either go into the admin side and clear and re-index, or run: `terminus drush <site> -- search-api:index`
=> YALB-1370: Bug: Search results for "Bread" and "Crumb"

composer.json, web/profiles/custom/yalesites_profile/composer.json
- Removes the use of wikimedia/composer-merge-plugin to install chosenJS
- Use `installer-paths` to properly place chosenJS into the correct location
=> Hotfix: ChosenJS Composer Install Fix

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
The current issue is that when a view is accessed that was previously created using the Drupal autocomplete results in a truthy value (a 1) being placed for the ID, so that taxononmy term is used for all views matching this.  This fix properly evaluates whether the term is an object (the Drupal autocomplete) or an id (the chosen autocomplete) and has been extracted to its own private method to start to separate concerns.
- Evaluates the state of the data to determine the best way to get the node id
- Extracts this logic into its own private method for separation of concerns
=> YALB-1518: View missing on resource library

web/profiles/custom/yalesites_profile/composer.json
Instead of allowing an ajax validation of whether a redirect happens to be an existing real path, move this into the server validator, allowing a successful save without needing to blur first.
This patch eliminates the ajax request from returning errors, and moves validation logic that the javascript version had into the form validator on the Drupal side.
Keep in mind, neither hindered users that really wanted to add a redirect to an existing real path; it was just a warning with a suggestion.
Known issue: https://www.drupal.org/project/redirect/issues/3057250
- Add [patch 65 from issue site](https://www.drupal.org/files/issues/2023-08-09/3057250-65.patch)
- A new tab/page will open
=> YALB-1538: Bug: Node redirects do not work

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Fixes uploading and editing of images
=> YALB-1495: Fix image uploading and editing

web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.install
The default node_access entry is added from core when there are no other access entries in the node_access database.  However, all queries include that for access, resulting in our own ys_node_access permissions being bypassed due to this being present.  This removes the entry from the database as it appears that it is a catchall if you were not use any specific node_access requirements.
- Rebuilds the node access permissions to remove the `nid: 0` entry in an update hook
Note: Search also adheres to this, so a CAS required page will not show in the results for anonymous users.
=> YALB-1382: Bug: NetID Required on node does not restrict page

web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.info.yml
A fix for [YALB-1382: Bug: NetID Required on node does not restrict page](https://github.com/yalesites-org/yalesites-project/pull/397)
While manually installing worked, build-on-install imports errored due to not loading the node module to make node_access_rebuild available to the install method of the ys_node_access module.
My setting node as a dependency of this module, it knows to load this beforehand and successfully runs.
- Adds node as a dependency of the `ys_node_access` module
NOTE: Also creating this as a PR to test how it does on fresh multidev deployment.
=> YALB-1382: Bug: NetID Required on node does not restrict page fix

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Added `ys_core_taxonomy_term_update` hook to clear rendered cache
=> YALB-1539: Bug: Taxonomy terms do not update in post feed or calendar list visually until user hits "Apply"

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/js/views-basic.js, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
- Changes the any/all labels in the view block form to:
- Any: 'Can have any term listed in tags and categories'
- All: 'Must have all terms listed in tags and categories'
- Move the any/all match section to be next to the tag inclusion/exclusion fields
- Ensured that javascript selection still functioned
- Modified the CSS to give these items a little more breathing room on the sidebar as the text was bleeding out of the boundaries of the label
=> YALB-1446: Feedback: Views UI Matching Labels

.github/workflows/build_deploy_and_test.yml
- Remove tmate debug step in Github Actions deploy job. It was useful when developing but now prevents action runs from failing fast.
=> CI: remove tmate debug

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_heading.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_link.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_text.yml
- Rename `CTA Banner Heading` label to `Action Banner Heading`
- Rename `CTA Banner Content` label to `Action Banner Content`
- Rename `Link` heading for the link widget to `Call-to-action`
=> YALB-1428: Bug: Action Banner Field Labels

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/key.config_override.mailchimp_transactional_api_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v2_secret_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v2_site_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v3_secret_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v3_site_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.key.mailchimp_transactional_api_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v2_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v2_secret.yml, web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v3_key.yml, web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v3_secret.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/ys_captcha.info.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/ys_captcha.module, web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.info.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.module, web/sites/default/settings.php
- Adds [Pantheon Secrets](https://www.drupal.org/project/pantheon_secrets) and [Key](https://www.drupal.org/project/key) modules so that secrets can be sourced directly from Pantheon Secrets Manager
- Adds Key module config overrides to replace items with values sourced from Pantheon
- Removes `ys_secrets` module as a dependency for `ys_captcha` and `ys_mail` modules, setting form overrides directly in `ys_captcha` and `ys_mail`
- Removes logic from `settings.php`
- [YALB-1541: Remove ys_secrets](https://yaleits.atlassian.net/browse/YALB-1541)
=> YALB-1242: Use Pantheon Secrets

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.info.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- It was discovered that with some custom code, if a node didn't have a menu item attached and you saved the node, it would mess up the site and prevent nodes (and the menu form) from being viewed and instead give missing route errors.
- This PR removes the custom code and to edit menu item extras (the heading CTA), content editors need to go into the menu item itself and can't be done on the node form.
=> HOTFIX: Fix Nodes not able to be viewed if no menu item

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_link.yml
- Makes link field for Content Spotlight optional
- Double checked that no atomic/CL changes were needed
As stated in the Jira ticket:
Example: https://yalesites.yale.edu/our-vision-guiding-principles Guiding principles would work very well in cascading Content Spotlights, but the required single CTA link prevents this Block from being used as intended.
A proof of concept for this is using the modified content spotlight is at [https://pr-418-yalesites-platform.pantheonsite.io/daves-content-spotlight](https://pr-418-yalesites-platform.pantheonsite.io/daves-content-spotlight)
=> YALB-1462: Bug: Content Spotlight Requires Link

web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/UpdateExistingNodes.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.deploy.php
- Updates existing events to disallow adding new sections
=> Event Sections

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/starterkit_config/.htaccess, web/profiles/custom/yalesites_profile/config/starterkit_config/migrate_plus.migration.ys_images_files.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/migrate_plus.migration.ys_images_media.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/migrate_plus.migration.ys_menu_links.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/migrate_plus.migration.ys_pages.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/migrate_plus.migration.ys_posts.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/migrate_plus.migration.ys_terms.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/single_content_sync.settings.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/system.action.export_content.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/system.action.export_media.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/system.action.export_taxonomy.yml, web/profiles/custom/yalesites_profile/config/starterkit_config/views.view.manage_taxonomy.yml, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/single_content_sync.settings.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.export_content.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.export_media.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.export_taxonomy.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.export_media.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.export_nodes.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.export_taxonomy.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.media_library.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/src/Plugin/Action/MediaBulkExport.php, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/src/Plugin/Action/TaxonomyBulkExport.php, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/src/Plugin/SingleContentSyncFieldProcessor/Embed.php, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/src/Plugin/SingleContentSyncFieldProcessor/Markup.php, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/src/Plugin/SingleContentSyncFieldProcessor/SmartDate.php, web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/src/Plugin/SingleContentSyncFieldProcessor/ViewsBasicParams.php
- Add [single content sync](https://www.drupal.org/project/single_content_sync) and supporting functionality around it for successful exporting of content/media/taxnonomy via views
- [Patch ZipArchive](https://www.drupal.org/project/single_content_sync/issues/3364535) for single content sync
- Create export code for media and taxonomy terms
- Creates new views for nodes, media, and taxonomy off of `/config/system` to assist in graphical exports
The reason the `--all-content` flag is not used is that it includes block_content as well.  If we'd like that, then --all-content could be passed to the first node version and it would return them all.  Technically since the UUIDs would be the same, it should be ok, but I'd be more explicit of what we're targeting.
Due to the size of the content …
=> YALB-1550: Single Content Sync

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Adds and enables `role_delegation` module
- Sets up `role_delegation` to only allow `site admins` to set `site admin` permission levels
- Update CAS bulk update form to use the `role_deleagation` module's settings to determine options to select from
NOTE: I noticed that each time our users log into the site via CAS, it gets the `Platform administrator role`.  My assumption given the CAS group name used is that this does not happen for our users of the platform.  If this is incorrect and any logged in CAS user gets this outside of our group, please let me know.
=> YALB-1554: Remove "Platform admin" from options for site admins when adding or managing site users

web/profiles/custom/yalesites_profile/config/sync/chosen.settings.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.profile.default.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml, web/themes/custom/ys_admin_theme/css/gin-custom.css
- Filter "Content" view and "Manage Pages" by tags
- Filter "Manage Posts" by tags and/or post categories
- Filter "Manage Events" by tags and/or event categories
- Filter "Manage Profiles" by tags and/or affiliation
=> YALB-1303: Finding content tagged with a specific tag

web/profiles/custom/yalesites_profile/config/sync/pathauto.settings.yml
Before, we were removing filler words in the URL generation, such as 'a', 'the', 'this', 'that', etc.  We no longer wish to remove these, so urls will now include these filler words as well going forward.
- Stops Pathauto from removing strings when generating a URL alias for a node.
=> YALB-1373: Feedback: URLs with filler words

web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/css/ys_toolbar.theme.css
On mobile, the Yale logo present in the admin-tools section of the menu has no text associated, making it look strange.  This hides that list item all together so that it only shows when the vertical menus are not visible.
- Adds css to `ys_toolbar` to hide the vertical list item for `tools-help`
=> YALB-1385: Feedback: Yale Logo with submenus

web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/UpdateExistingNodes.php
- Adds a condition to the layout builder update hook to ensure content exists before updating the content.
- I have tested this locally to ensure it does not have any negative impacts. Since this is an update hook, it will not run on other environments so the scope is limited to Berkeley Divinity. I'm happy to setup a sandbox for testing if we want a more comprehensive test plan.
=> YALB-1566: Fix deployment for Berkeley Divinity

web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PostMetaBlock.php
- Fixes search indexing that was being halted by an error with the PostMetaBlock.
- Multidev testing here - https://pr-443-yalesites-platform.pantheonsite.io (Note this PR isn't connected to that multidev, and that PR was closed, so the multidev could go away at anytime)
- Local testing works too
=> fix(YALB-1569): Fix search indexing prevented by PostMetaBlock issue

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Adds the ability to override the header menu link CTA text from within the page add/edit form.
=> YALB-1564: Header: Mega Menu Description Link

docs/color-theme.md, web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-footer-block.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/levers.css, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/js/levers.js, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
- Remove themes `four` and `five`
- Updates themes `one`, `two`, and `three` to match the following color slots
- Adds header accent and footer accent
https://github.com/yalesites-org/yalesites-project/assets/366413/aac31233-148d-4039-95b5-a4f3bed61496
=> YALB-1562 - Color: Update tokens for existing color palettes - remove global themes 4 and 5 - add header accent, footer accent

web/profiles/custom/yalesites_profile/composer.json
A regression introduced in drupal/linkit 6.0.1 is causing PHP fatal errors when editing site settings. This PR pins linkit to 6.0.0.
=> hotfix: pin drupal/linkit to 6.0.0

composer.json, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.quick_links.field_text.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
- Sets `field_text` of `quick_links` block to `heading_html` format
- Create update hook to sanitize any existing `quick_links` content to remove any links and set the format of it to `heading_html`
=> YALB-1443: Bug: Disable links in quicklink content field

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_position.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_variation.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_width.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_position.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_width.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_style_position.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_style_variation.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_image.field_style_position.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_image.field_style_variation.yml
- Update all block dials (style fields) to make sure they are required and include `default_value_callback: ys_themes_default_value_function`
=> YALB-863: Set default value callbacks for all block dials

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.condensed.yml
- Update the fields formatter to use 'plain' text instead of the 'smartdate' format. This ensure the time is passed to the component library in the correct format.
=> YALB-1577: Fix time format on condensed events

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Passes properties from the theme settings form via #context array to prevent render array errors.
=> YALB-1579: Fixing theme form error messages

web/sites/default/settings.php
- Support site-specific settings like config splits, etc. by loading a site-specific Pantheon settings file if one exists
=> Support loading site-specific settings.php files

web/profiles/custom/yalesites_profile/composer.json
- Add block_content_permissions module back since having it removed is causing D10 upgrades to throw errors and puts sites into maintenance mode
=> hotfix: re-add block_content_permissions module

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.pull_quote.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quick_links.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.wrapped_image.default.yml
- Adds patch to allow CKEditor to calculate `--ck-min-height` variable based on rows defined
- Adds min-height to CKEditor displayed "text area" spaces to respect `--ck-min-height`
- Changes a multitude of block content rows values to 3
- Changes a multitude of block content rows values to 3
This branch is now based on master with D10, not needing the patch that was used previously to create the multidev.  For the truest experience of the result, bring local with D10.
=> YALB-961: WYSIWYG: Text field size to reflect character limits

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.accordion.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.custom_cards.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.directory.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.event_list.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.gallery.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.media_grid.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.post_list.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.pull_quote.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quick_links.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.view.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.webform.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.accordion_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery_item.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tab.default.yml
- Changes soft limit field maxlength text to read: "Content recommended length set to `@limit` characters, remaining: <strong>`@remaining`</strong>"
=> YALB-1387: WYSIWYG: Clarity on maxlength

pantheon.yml, web/private/scripts/confim.php, web/private/scripts/drush_deploy.php
`drush deploy` that runs in CI was getting no output because it was first running on the platform from Quicksilver. This updated script uses Pantheon's workflow API endpoint to check if the sync_code hook was initiated by our machine user or not. This commit also renames this file and references in pantheon.yml, since it is now doing more than just a config import.
=> Add conditional logic to `drush deploy` quicksilver script

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
This attempts to fix a bug that was found with the header implementation.  isFrontPage does not seem to take into account aliases.
We get around this by getting the node id of the page, the alias of the page, and the current front page that is set in site settings.  We then determine if it is the front page if the location set in the site settings matches either the node id path or the alias path, or if isFrontPage thinks it's a front page.
- Checks the site settings front page setting against the current page's node and alias to determine whether to display the focus header.
=> YALB-1574: Branding: Header Variation Backend Front Page Alias Fix

web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
- Adds permissions for site admins and platform admins to add/edit/delete affiliation terms.
- Defines a link to manage affilation terms in on the content menu.
=> YALB-1573: Allow admins to manage affiliation terms

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
A user reported an issue with their site throwing fatal errors:
```
Uncaught PHP Exception Error: "Call to a member function getFileUri() on null" at /code/web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php line 87
```
They had one footer logo uploaded and the other instance of the field was returning as `null`. This checks to make sure an instance of the field is not null.
=> YALB-1648: Bug: empty footer logo instance causes PHP fatal error

web/profiles/custom/yalesites_profile/composer.json
Quick Node Clone does a great job of cloning, however, when it attempts to clone a node with layout builder, it does not correctly clone the inline blocks and paragraph references we use.  This is a more global issue, and a patch has been worked on to fix this.  This patch fixes our issue and sub-items are properly cloned and editable.
References: https://www.drupal.org/project/quick_node_clone/issues/3100117
Patch Reference: https://www.drupal.org/files/issues/2023-04-25/quick-node-clone--inline-blocks--3100117-32.patch
- Add patch to enable inline blocks and paragraphs to be cloned properly through Quick Node Clone
=> YALB-1602: Bug: Clone nodes with accordions and callouts wont allow user to edit

web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
- Temporarily removes the block library visibility from site admins
- Once reusable content is merged, we can re-enable block library access
=> YALB-1654: Reusable Content Prep: Remove or add message to block library

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.background_image_16_9_focus_header.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Fixes bug when site admins attempted to add media to blocks.
- Restores access to custom block library to all roles
- Adds help text on top of the custom block library to describe the purpose
=> YALB-1654: BUG FIX Reusable Content Prep: Remove or add message to block library

web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.module
- Define the $private variable at the top of ys_node_access_node_access_records()
`
Warning: Undefined variable $private in ys_node_access_node_access_records() (line 55 of profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.module).`
=> YALB-1629 Fix node access warning

composer.json
- Drupal 10.2 being installed due to loose version constraint in composer.json which is causing problems on new sites. Pin to Drupal 10.1.7.
=> hotfix: pin drupal 10.1.7

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.text.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.text.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.text.field_style_variation.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
- Adds variation option to the `text` component for `emphasized`
- Themes the emphasized variation to use the body-xl style: https://yalesites-org.github.io/component-library-twig/?path=/story/tokens-typography--body-styles
- Note branched PRs in Atomic and Component library:
- https://github.com/yalesites-org/atomic/pull/191
- https://github.com/yalesites-org/component-library-twig/pull/315
=> YALB-1306: Emphasized text

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.callout.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.callout.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.callout.field_style_alignment.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_style_alignment.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
- Adds alignment variable for `callout__alignment`
- Adds a default of `center` - existing callouts will render the same
- Adds a `field_style_alignment` field in Drupal, default is `center`
- Wires the `callout__alignment` variable to `field_style_alignment`
- You can choose between `center` and `left`. `center` uses the `site` width. `left` uses `content` width to restrict the callout inner wrapper width.
https://github.com/yalesites-org/yalesites-project/assets/366413/7ffa0d73-fc07-4d37-bb65-814f98585148
=> YALB-1644 - Dial: Center-align callout with content-width content

composer.json, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.extension.yml, web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml, web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml, web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml, web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
- Installs and enables `anchor_link` module
- Adds the anchor link button to the `basic_html` and `restricted_html` text formats
- e.g. If anchor `anchor1` is set to the bottom of a page `Test Page`, then loading the url `/test-page#anchor1` will load at the bottom of `Test Page`
=> YALB-1169 Links: Enable WYSYWIG tools for anchor links

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
There was a problem where a user deleted the default content section. Upon saving this, they were unable to go back in to modify the page in layout builder.  This was due to an access check issue in section_library.  This patch fixes this so that the user could edit the page in layout builder again.
- Adds `section_library` patch to allow access check to not throw an exception
- [Section Library Issue](https://www.drupal.org/project/section_library/issues/3241715)
- [Section Library Patch](https://www.drupal.org/files/issues/2022-09-21/3241715-6.patch)
=> YALB-1663: User getting error page when clicking "edit layout and content" in top menu

scripts/shared/content-import.sh
- Changes the content import script to use a variable for the remote environment, and falls back to `dev`. This allows us to set the environment from outside the script if needed.
=> feat: content on install to environments other than dev

web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_media_file.yml
- Adds rtf files to the list of allowed file types on the document media entity
=> YALB-1686: Allow rtf file uploads

.ci/github/create_release_pull_request
- When updating release PRs, filter out merge commits that caused `jq` parsing errors
=> fix: filter out merge commits that do not have a PR (actions create PR workflow)

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.quick_links.field_text.yml
In updating develop from master, the allowed_formats were overwritten from before.  This re-establishes this for new quicklink blocks.
- Ensure that new Quicklinks blocks do not allow links
=> rel-100-quicklink-format-fix: Re-introduce heading_html format

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_heading_level.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_heading_level.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.text.field_style_variation.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_heading_level.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.export_content.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesTitleBreadcrumbBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PageMetaBlock.php
- Adds help text for heading override fields on page title blocks and banner blocks.
- Exports configuration which updates two files with non functional changes.
=> YALB-1513: Improve help text for title/heading control fields

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
This will also close [YALB-1633](https://yaleits.atlassian.net/browse/YALB-1633) as the field won't be visible any longer at the location, so including this in the acceptance of this ticket.
[Component Library PR](https://github.com/yalesites-org/component-library-twig/pull/320)
- YALB-1685: Removes the `Mega Menu Top Level Link Text` field from the sidebar menu section of `Manage Settings`
- YALB-1685: You will still be able to access this via the `Manage Main Menu` view
- YALB-1667: In basic menu, allows the parent page title to be the submenu heading in the basic header menu
- YALB-1667: In the event the parent menu item is not linked to a node, it will revert to the parent menu item title
[YALB-1633]: https://yaleits.atlassian.net/browse/YALB-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> YALB-1685: Bug: Error when going to "Manage Settings" on certain pages

web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
- https://github.com/yalesites-org/yalesites-project/pull/541
=> fix: YALB-959 - revert site admin access block library permission

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
In getting the release ready, the YaleSites portion of the menu fix was not included in the release.  This cherry-picks the commit to be included such that sites will properly display a submenu top level item for basic menus.
- Cherry-picked develop commit to be included in hotfix
=> rel-100-hotfix: Submenu Display Fix

web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/block-form.js, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Add method to have a better attempt to get the block type
- Modified block form JS to revert to providing the error message to the submit button if the input targeted is not visible.
On develop for now so we can test, then will move to master for hotfix inclusion.
[YALB-959]: https://yaleits.atlassian.net/browse/YALB-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> YALB-1696: Hotfix: Can't configure Page title as Site admin

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
There were some sites who had link references in their top level menus, resulting in errors attempting to get a valid node. From what I can tell, having a still results in a menu item showing as "routable", even though a node does not exist on it. This patches this by checking each variable exists and to check that a node param exists on the routable parameters. It should also guard against any other cases where it thinks it's routable but has no node.
- Adds guard checks to node detection
=> REL-100 Hotfix: add guard clauses to bypass <nolink>

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/CoreTwigExtension.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceManager.php
MultiDev PR: https://github.com/yalesites-org/yalesites-project/pull/467
Component Library PR: https://github.com/yalesites-org/component-library-twig/pull/319
Atomic PR: https://github.com/yalesites-org/atomic/compare/YALB-520-links-dynamically-apply-link-treatments
- Shows off link treatment work completed now in component library twig
- Links decorated:
- External
- Downloads
- Target Blank
__Keep in mind scope was change to not include mailto and telephone decorations until more design and feedback is completed.  Anchors are no longer decorated as other decorations handle it (local vs external).__
=> YALB-520: Links: Dynamically apply link treatments

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
… content type styling
- Adds body class with content type for specific content type styling
=> YALB-1568: FE Bug: Profile page breadcrumb issue

web/profiles/custom/yalesites_profile/composer.json
This was found while e2e testing locally, and I've experienced this randomly throughout working on different tickets where a deprecation warning is displayed on `dateFormatter`.
While fixed, smart_date 4.0.3 is not released yet, and we don't want to point to dev.  This patch adds a dateFormatter to the class using it instead of relying on the parent class to provide this, causing the deprecation.
Once 4.0.3 is released or we decide to bump to 4.1.x release, we can remove this.
- Add patch to have dateFormatter be on the class in question
Hard to reproduce, but this was the latest I was able to:
=> YSP-324: Deprecation warning in smart_date causes axe to find issue

.ci/github/clean_up_multidevs, .ci/github/create_release_pull_request, .ci/github/deploy_release_sites, .github/workflows/release_pr.yml, package.json
This PR updates the automation of pull request creation for releases. Highlights:
- Updates to use latest version of [semantic-release](https://github.com/semantic-release/semantic-release)
- Runs on `workflow_dispatch` to allow for creation of a "release pull request"
- The next release number is derived from the changes in `develop` and a release branch with this name is created
- Pull request is created with summary of all changes in the release branch
- Testing multidevs are created and release branch is pushed to them
- A comment is posted with environments for review
- yalesites-reviewers team is added as reviewer
- Runs automatically on specific `pull_request` events:
- `synchronize` for any new pushed changes
- `close` to clean up generated environments and reset repo tracking …
=> Update release pull request action

.github/workflows/release_pr.yml
- Sets `RELEASE_BRANCH` based on if it is available from a step output or repo variable
=> Github Actions: fix retrieval of release branch in release pull request creation

.github/workflows/release_pr.yml
- Sets unique cache key for `release_pr` job to prevent sharing with other jobs where credentials may be missing
=> Github Actions: set unique cache for release_pr job

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.directory.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileContactBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php
- Allows views to use external link if available for correct decoration
- Adds field_external_source to profile directory config to pass to twig
- Adds field_external_source to search content types to pass to twig
- Modify search_api to use default rendering of profiles for search
- Fixed backend errors regarding profile data access
=> YSP-355: External view results don't have external icon

.ci/github/deploy_release_sites
- git connection info was being derived from the included environment, and this would fail for sites that are sourced from `live`. We can hardcode `dev` here to make sure we always get the correct git info.
=> Github Actions: always derive git info from dev environment

patches/layout_builder_browser/3408935-and-3409153-8.patch, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
- Adds `Spotlight - Portrait` to available reusable blocks for block picker
- Rename `Global Block` to `Reusable Block` in block picker
=> YSP-371: Reusable Blocks created via backend not available in Block Picker

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
- Adds an update hook to update the front page to a /node/<number> format if it is set to an alias.
=> YSP-373: Front page not updated to node reference

web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
- Adds permissions to clone profile for site/platform admins
=> YSP-318: Can't clone a profile

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
- Fixes site wide error if any footer logo media was deleted in media library before being removed from the footer config.
Note: What this code does is actually delete out the missing config ID of the deleted footer media if any was set. Therefore, there is an admin message that gets output at the top of the page that tells the content editor that:
"Note, one of the footer logo images has been deleted. You may set a new one in the footer settings form" with a link to the form.
=> YSP-414: Deleting used content.school_logo media results in site wide page errors

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Guards against loading of deleted focus header image on render
- Add a way to clear when multiple values of an image are stored where one doesn't exist
=> YSP-374: Deleting focus header image results in sitewide error

package.json
- Add version number to yalesites_profile when new release is created
- Commit the change and backmerge it to `develop` branch
=> YSP-432: Add version number to yalesites_profile

web/profiles/custom/yalesites_profile/composer.json
- Adds the ai_engine module to the platform
- The module is not enabled or configured so there are no functional changes
- Nothing to test. This simply gets us one step closer to bringing all of the AI sites into sync with the main platform.
=> AYH-20: Add ai_engine to platform

web/themes/custom/ys_admin_theme/css/gin-custom.css, web/themes/custom/ys_admin_theme/css/gin-custom.css.map, web/themes/custom/ys_admin_theme/scss/gin-custom.scss
- Changes background color of preview link to use gin in order to pass A11y contrast requirements
=> YSP-437: v1.2.0: Media preview link contrast issue

patches/selective_better_exposed_filters/selective_better_exposed_filters-3432551.patch, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/views.view.directory.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.post_list.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Hides exposed filters if there are no options.
I originally wanted to add a class to the form if there are no options and then hide it using CSS but it's Jim's preference that the component library not be involved on this one. So, in-line it is.
I also tried unsetting the options and submit button but that leaves a gap visually because the form is still there, adding its height.
=> YSP-302 Hide empty exposed filters

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.media_library.yml
- Make image media library form display unique
=> YSP-440: v1.2.0: Focal point not present in block media add

.github/workflows/release.yml, package.json
- Semantic Release Backmerge was added in v1.2.0 to keep develop up to date with master after a release, but it failed. This PR switches the merge strategy to `merge` instead of the default `rebase`.
- `develop` is also a protected branch so I'm setting actions/checkout step [per the docs](https://github.com/saitho/semantic-release-backmerge?tab=readme-ov-file#backmerging-into-protected-branches)
=> Semantic release backmerge updates

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.media_library.yml, web/profiles/custom/yalesites_profile/config/sync/image.style.media_library.yml
Pam reported the media library images are very slow to load after a cache flush. After debugging, the media library display mode was not enabled for media library images, so full size images were loading and being scaled down.
This updates the media library thumbnail style to use focal point and increase to 350x350 for clearer previews, and
enables the Media Library display mode for the Image media type.
=> YSP-470: Media library images slow to load

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.grand_hero.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_link_two.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_link_two.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_link_two.yml
- Adds optional second link field for cta banner and grand hero banner
- Adds a button-group wrapping div to preserve the existing space between elements
- Adds a new `field_link_two` field and re-uses it for each banner - adjusting the label to match the first link's pattern
=> YSP-430: Canvas user need to allow two call to actions in banner

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileContactBlock.php
- Adds safety checks for retrieving data in the profile content block
- Restricts YaleSite layout blocks for events and posts
=> YSP-478: Bug: Adding Profile Content Block to Post/Events results in error

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
- Content editors can no longer remove default blocks placed in the banner section.
=> YSP-529: V1.3.0: remove the configure button on moderation placeholder in /layout

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
* [YSP-529: V1.3.0: remove the configure button on moderation placeholder in /layout](https://yaleits.atlassian.net/browse/YSP-529)
* [YSP-530: V1.3.0: Reusable Reference Card doesn't show up in block picker](https://yaleits.atlassian.net/browse/YSP-530)
* Multidev testing: https://pr-652-yalesites-platform.pantheonsite.io/
- Disallows removing of the content moderation block in the banner section
- Adds the reference card reusable block to layout builder browser to pick previously created reference cards
=> YSP-529/530 - Layout builder fixes

web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml
Since we are using content moderation, using the existing bulk operations of publish and unpublish result in a warning notifying the user of the use of content moderation, followed by error messages reinforcing the same thing.  Since this is now not able to be done, we remove these options from being selected in the bulk operations drop down.
- Remove `publish` and `unpublish` from possible bulk operations in the following views:
- Content
- Manage Events
- Manage Pages
- Manage Posts
- Manage Profiles
- This originally allowed all bulk operations instead of a subset as the other did.  This also makes Profiles behave like the others by limiting the bulk operations to a subset.  They now all match.
=> fix(YSP-525): v1.3.0: Bug: Bulk publish/unpublish operations do nothing

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_content_ref.yml
After reviewing the naming of the fields of the reference card, it was determined that Content was not as informative than something like 'Reference source'.  This change renames 'Content' to 'Reference source', and adds help text to help the user know what the use of it is.
- Renames `Content` to `Reference source` for reference card block in Drupal
- Adds help text to the field for `Reference source`
=> fix(YSP-526): V1.3.0: Reference Card Label Change

web/profiles/custom/yalesites_profile/config/sync/views.view.media.yml
While users can add tags, there wasn't a usage for them yet in the system.  This was a way to still convey that entering this can be useful by giving them a chance to filter via the media table by tags and see what tags are assigned to a media.
This adds both a tags filter using Drupal's autocomplete, and a tags column to display tags associated with media.
- Adds tag filter for media table view
- Adds tag column for media table view
Note: You might need to add some media or add tags to see this functionality.
=> fix(YSP-528): V1.3.0: Media Library add tag column in view

web/profiles/custom/yalesites_profile/config/sync/block_content.type.content_spotlight_portrait.yml, web/profiles/custom/yalesites_profile/config/sync/block_content.type.directory.yml, web/profiles/custom/yalesites_profile/config/sync/block_content.type.reference_card.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.callout.field_style_color.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_color.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight_portrait.field_style_color.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_style_color.yml
- Check the option 'Create new revision' for all blocks.
- Use the label 'Theme' in the field field_style_color.
-  Alignment
- Columns
- Position
- Style
- Theme
=> YSP-517: Tech debt consistent field settings

web/profiles/custom/yalesites_profile/config/sync/gin_lb.settings.yml
- Hide the 'Revert' button from the layout builder setting.
**Before:**
**After:**
=> YSP-521 - AX: Hide Revert button on layout builder

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- Adds proper alignment for reusable accordion blocks in posts and events
=> YSP-479 Wrong alignment for Reusable Blocks in Posts, Profiles and Events

web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
- Gives permissions to platform admins to assign contributor and editor roles
=> YSP-540 give permissions to platform admins to assign roles

web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
_Note: Even though the branch is on a hotfix branch, this is no longer a hotfix._
On a published node, adding it to the menu via the sidebar resulted in Pathauto erroring due to the menu-item not being handled correctly.
This is an interaction issue between Pathauto, Token, Content Moderation, and Workflow Buttons.  Adjusting the weights of Pathauto and workflow buttons ensure that the menu item gets saved correctly, and that the alias is properly updated without needing to do a 2nd publish.
- Changes the weights on `pathauto` to occur later
- This fixes pathauto having to save twice to get the correct parents
- Changes the weights on `workflow_buttons` to occur earlier
- This fixes the tokens not being able to load the menu item from the `menu_tree` before it exists
=> YSP-538: Provide a menu link error on Publish

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
-  Replace the word 'terms' with 'tags or categories'.
=> YSP-299 - Update "term" description in Views block]

web/profiles/custom/yalesites_profile/config/sync/field.field.media.background_video.field_media_video_file.yml
- Increases the max file size of a background video from 12 MB to 25 MB
=> YSP-532: Increase grand hero video size maximum

web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/MetaFieldsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.info.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
- Adds `stream_url` and `stream_embed_code` to Events
- Adds contextual styles to allow optional fields to expand/contract as needed
- Adds `reference_heading__prefix` to wire `event_title__prefix` for event reference cards
https://github.com/yalesites-org/yalesites-project/assets/366413/69733a39-9ce1-49c3-b088-1119bc87d75e
---
https://github.com/yalesites-org/yalesites-project/assets/366413/d22383f8-3e65-4fb5-978d-9690818c1a82
=> YSP-560: Localist: Update Event lists + default image updates

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/js/levers.js
- Adds the CTA button to the header if the CTA fields are populated in the header form
Requires https://github.com/yalesites-org/component-library-twig/pull/370
=> YSP-431 Wire/Add/Tweak Call-to-Action button utility nav

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
- Allow the blocks Spotlights (Landscape, Portrait) to be added to the 'Banner' section
- Basic:
- Advanced:
=> YSP-494 - Allow content spotlight as a banner

web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
While the standard view for the views block was using the proper sorter, the event specific one was not.  This lets it use it to drive the sort operation.
- Makes the event-specific views "view" to use the `basic_views_sorter`
=> YSP-588: Pagination after first page doesn't comply with ascending/descending dates for events

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/js/views-basic.js, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
- Move logic from Drupal array to Javascript
- Reinstates original intent
- Limit hidden only if 'all' display selected
- Limit label updated depending on display value:
- 'limit': "Items"
- 'pager': "Items Per Page"
=> YSP-570: Views: Change limit help text

web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
While looking at another issue, we noticed that the permissions for the new blocks were not set.  While this doesn't hinder users from using them due to relying on Layout Builder Restrictions, it is our convention to still enable them in case another module relies on these.  This enables them to mimic other blocks in the past.
- Enables permissions on new blocks matching that of older blocks
=> YSP-576: Enable new block permissions

web/profiles/custom/yalesites_profile/composer.json
- Bump ai_engine module to 1.2.3
=> YSP-613: Bump ai_engine in YaleSites to 1.2.3

web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.services.yml
- If we can't get a taxonomy, make the name an empty string
=> YSP-611: Localist: Views errors after localist enable

.github/workflows/build_deploy_and_test.yml
- Sets `repository` during actions/checkout workflow step to allow runs from forked repos and falls back to the default if not set.
More info: https://github.com/actions/checkout/issues/551#issuecomment-1154421608
=> fix: allow actions/checkout to run on forked repos

.github/workflows/build_deploy_and_test.yml
- Switch the build_deploy_and_test workflow to use trigger pull_request_target instead of pull_request for better forked repo support.
=> fix: switch to pull_request_target trigger for forked repo support [skip ci]

web/profiles/custom/yalesites_profile/modules/custom/ys_localist/migrations/localist_events.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.module
- Adds `process_row` hook to help fields ending in `_url` to have a protocol if it was missing
- Allows the `field_event_cta` to be overwritten on localist sync changes
=> YSP-623: Localist: URL field not getting stored properly, and is not getting updated upon syncing

web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
- Adds new blocks to be included in layout builder browser reusable selections
=> YSP-626: New Block are not saving as reusable

web/profiles/custom/yalesites_profile/composer.json
- Bumps the pinned version of ai_engine to 1.2.4
=> YSP-633: Bump ai_engine to 1.2.4

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.pull_quote.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quote_callout.default.yml
While creating the AI website, there were quotes that were just over the hard limit of 425.  Instead of gradually increasing this, it was decided to remove the hard limit, allowing those that wish to still go over to do so.
- Pull Quote Block now have soft limit enabled
=> YSP-639: Change quotes to soft limit

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/README.md, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-event-meta-block.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
- e4acea3dbe70b7dcf0c21a74d5cd649947948b4c
- e93e16bfeb6a3ff25daa144351ef834e74b5f373
- bc3172982658487af2d3e4cba2b6d87fadc84ced
=> Hotfix: YSP-649: EDT vs EST from Localist causing incorrect time render [skip ci]

web/profiles/custom/yalesites_profile/composer.json
- Adds [patch](https://git.drupalcode.org/project/google_analytics/-/merge_requests/36.patch) from [known issue](https://www.drupal.org/project/google_analytics/issues/3275926) to guard against NULL accounts in Google Analytics module
=> YSP-631: GaAccount::__construct(): Argument #1 ($account) must be of type string, null given

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.video.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.video.field_style_alignment.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
Work also done in--please review also:
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/414)
- [Atomic](https://github.com/yalesites-org/atomic/pull/266)
- Adds `field_style_alignment` to video block
- Sets component overrides for video block's new dial
See Atomic note, but we are force centering videos on posts and events; I left this unchanged.
=> YSP-662: PRESIDENT: allow center or larger view of video block

web/profiles/custom/yalesites_profile/config/sync/system.action.publish_moderated_content.yml, web/profiles/custom/yalesites_profile/config/sync/system.action.unpublish_moderated_content.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedPublish.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedUnpublish.php
- Adds a bulk unpublish option with content moderation
- Adds a bulk publish option with content moderation
=> YSP-647: PRESIDENT: Ability to bulk Unpublish

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Passing the integer value of the operator resulted in the item not being properly selected in the form view.  This fixes this.
- Stops passing integer value to the form for the Can/Must selection; send string instead
=> YSP-652: Views setting Can or Must selection is not selected on configure

web/profiles/custom/yalesites_profile/composer.json
While this is a 10.3 fix, it seems to be working locally.  Wanted to get this on a multidev to try.
- Adds a patch for this known issue
=> YSP-671: Unable to Select Media for blocks with images by filtering

patches/typogrify/3398815.patch, web/profiles/custom/yalesites_profile/composer.json
- Upstream merge request for https://drupal.org/issue/3373921 changed and the patch no longer applies. Switch to a local version of this patch with just our changes from that issue, which applies to typogrify 1.2.
=> Switch drupal/typogrify patch to local version

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Because we have muiltiple places where Categories could be used, we don't want to specify that such that it's not misleading that this doesn't apply to the Jakala added filters.
- Changes the text displayed on the "Must include"/"Can include" to remove tags and category reference
=> fix(views-text): Change any/all text to not include category

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedPublish.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedUnpublish.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Service/LayoutUpdater.php, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/Plugin/migrate_plus/data_parser/LocalistJson.php, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/PostYearFilter.php
This adds linting fixes to previous commits that somehow did not find issues, but now does in new multidevs.  This is a way to not have to cherry-pick this commit fix in all other multidevs.
- Adds linting fixes so that multidevs can create
=> Fix linting issues on develop preventing multidev creation

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
We had a $cachable which was not even in the signature of options_allowed_values, yet we were passing something in that then wasn't even being used.  This lets it match the signature found at:
https://api.drupal.org/api/drupal/core%21modules%21options%21options.module/function/options_allowed_values/10
- Removes `$cachable` reference as we weren't using it anyway and it's not in the D10 signature
=> YSP-690: Deprecation of parameters with default values order

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.image_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image_banner.field_media.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image_banner.field_style_variation.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
- [Atomic](https://github.com/yalesites-org/atomic/pull/270)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/423)
- Adds image banner size dial to image banner (large or small)
- Mimics the grand hero layout and styling to have consistent feel
=> YSP-680: PRESIDENT: Add dial to image banner to allow default and large image display

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.profile.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.condensed.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.directory.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.single.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.profile.field_pronouns.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_pronouns.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
Other work needing review in:
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/422)
- Adds pronoun field to profile
- Allows display of this profile field in rendering
=> YSP-346: Add pronoun field

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml
- Increase max character limits on portrait spotlights from 500 to 650 characters
- Increase max character limits on landscape spotlights from 500 to 600 characters
=> YSP-693: Increase hard limit on spotlights to 650 characters

README.md
_Real work done in :_ [Atomic](https://github.com/yalesites-org/atomic/pull/272)
The div that is inserted for the item seems to be modifying how the image banner behaves, skipping the styling of it to match the grand hero.  By creating this, it allows it to bypass this, picking up the styles similar to the grand hero in Drupal.
- Adds a bypass to the item content so that the extra unsettled div does not get rendered
=> YSP-697: Image Banner not respecting focal point

README.md, web/profiles/custom/yalesites_profile/composer.json
Reverts yalesites-org/yalesites-project#778
=> Revert "YSP-697: Image Banner not respecting focal point"

patches/layout_builder_browser/3408935-and-3409153-9.patch, web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Changes also made in [Atomic](https://github.com/yalesites-org/atomic/pull/281); please review that as well.
- Uses correct array attribute to get changed time for sorting and display
- Update quick node clone to 1.19.0 for patch compatibility
- Remove "filter" words from filter list on views block
- Re-add event-based conditional displays on views block
=> v1.10.0: Multiple fixes

web/profiles/custom/yalesites_profile/composer.json
The latest changes to the quick node clone patch we use made it incompatible with 1.18.0.  It does work with 1.19.0.
References: https://www.drupal.org/project/quick_node_clone/issues/3100117
This is a cherry-pick since other vendors are running into issues using develop for work.
- Bumps quick node clone to 1.19.0 so the patch can apply
=> fix(v1.10.0): bump quick node clone to 1.19.0

composer.json
- Update Drupal core to [10.3.9](https://www.drupal.org/project/drupal/releases/10.3.9)
=> Update drupal core to 10.3.9

web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml
- Adds Last Updated By field to Content, Manage Pages, and Manage Posts views listings
=> IYY-267: Add Last Updated by to Content admin

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.media_library.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.media_library.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_metatags.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_metatags.yml, web/profiles/custom/yalesites_profile/config/sync/metatag.settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/Plugin/migrate_plus/data_parser/LocalistJson.php
There was a function signature that had changed, causing our existing LocalistJson parser to fail.  This places the signature in line with the subclass function definition.
References: https://www.drupal.org/project/migrate_plus/issues/3462520
- Updates the function signature to match it's parent class's
- Add `field_metatags` to document media type
- Bump Atomic to 1.39.2
- Bump AI engine to 1.2.7
=> Hotfix: Update LocalistJson function signature

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/search_api.index.secure_index.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.search_cas.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.header_settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Controller/SearchController.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.routing.yml
- Adds a new Search API index that searches CAS content by indexing the content as viewed by an authenticated user
- Adds a new view for showing CAS content
- Updates the header settings form to add a new option to show CAS titles only when searching. Default is off.
- Removes the `/search` path from the existing Search view
- Replaced with a custom route and controller to handle the `/search` path and only shows CAS content if set in the header settings form.
- Note: This requires Atomic [PR-284](https://github.com/yalesites-org/atomic/pull/284) as that is where the logic is to disable the rendering of the teaser and content preview of CAS nodes.
- A second FED part of this ticket will add a lock icon next to the CAS-only titles.
- All CAS content (rendered HTML default display) is still …
=> IYY-263: Show CAS'd content in search results

.github/workflows/release_pr.yml
The release_pr.yml workflow is triggered manually using workflow_dispatch, and on pull request synchronize/closed activities. It is running unexpectedly against other pull requests to master, like hotfixes. Since it currently does not need to run automatically against pull requests to master since we create release PRs using workflow_dispatch, this change sets it to only run on pull requests matching the release branch naming pattern.
=> fix: only run release_pr.yml workflow against release branch pattern, not master

web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Controller/EmbedInstructionsController.php, web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/PowerBI.php, web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceBase.php, web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceInterface.php, web/profiles/custom/yalesites_profile/modules/custom/ys_embed/templates/embed-instructions.html.twig
- Updates the Microsoft Power BI embed to allow for two different kinds of URLs (`/view` and `/reportEmbed`)
- Note - I think it should be fine, but, I would like to test this code on an existing site that has Microsoft Power BI embeds already being used. If anyone knows an existing site, please link it here and I will test that as well.
=> IYY-266: Ensure Microsoft BI embeds work

.github/workflows/release_pr.yml
b382a15 broke the behavior of release_pr.yml running when a release pull request was closed. This change triggers the workflow to run after running release.yml.
=> fix: run workflow after creating a release to clean up multidevs

.github/workflows/release.yml
release.yml currently runs when a push is made to master, but should be changed to when a PR is merged, since semantic-release bumps the yalesites_profile version during the release with an additional commit, which is making the action run twice.
=> fix: prevent release.yml from running twice [skip ci]

web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/PowerBI.php, web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install
- Adds an update hook to fix existing Power BI embeds to work with new Power BI code
=> IYY-266: Updates existing Power BI embeds to work with new Power BI embedder

web/profiles/custom/yalesites_profile/config/sync/cas.settings.yml
> When logging out of Drupal, if the home page is CAS-protected, the user is automatically logged back in because they still have a valid CAS session. This causes confusion because the redirection happens quickly and it appears the user is never logged out, even though they are.
- Sets config to log out of CAS when logging out of Drupal
- Returns user back to home page after logout instead of CAS Server default (www.yale.edu)
=> YSP-293: Log out of CAS when logging out of drupal

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesTitleBreadcrumbBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PageMetaBlock.php
- Bumps quick node clone to 1.20.0 to continue using patch
- Autofix newly found linting issues on build
=> Hotfix: YSP-791: Bump quick node clone to 1.20.0

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight_portrait.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_alignment.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight_portrait.field_style_alignment.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
- Adds vertical alignment option to  Spotlight - Landscape and  Spotlight - Portrait
- CL: https://github.com/yalesites-org/component-library-twig/pull/452
- Atomic: https://github.com/yalesites-org/atomic/pull/294
=>  IYY-302: Add vertical text alignment to Spotlights

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Since we are on D10.3 now, this should be fixed and so the invalidation of the cache should no longer be needed.
- Reverts #669
=> YSP-730: Revert changes made in #669

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
- Fixes an issue where with some views, there was a white screen error relating to an ambiguous nid in the query
- Please test with `ys-library-yale-edu`, @dblanken-yale
=> IYY-271: HOTFIX Fixes ambiguous nid error on some views

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/ys-themes.css
This displays the save button that is hidden by GinLb.  This makes me wonder the implications or the reason why they chose to do this across all dialogs, but it does work.  My real worry here is that users might not realize when they change the image that it will change the image for that media item--so they're not choosing a new image, they're replacing the current image across the site.
It also does not update the sidebar since it doesn't refresh the page on save.
- Shows the Save button for the media edit within a block edit dialog
=> YSP-760: Editing an image popup doesn't show save button

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
This work is dependent on the following other PRs--please review these as well:
- [Atomic](https://github.com/yalesites-org/atomic/pull/301)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/462)
- Added checkbox for displaying pinned items at the top of the list.
- Introduced pin label field to customize the label for pinned items.
- Updated form elements and massageFormValues to handle new fields.
- Implemented logic to sort pinned items at the top in ViewsBasicSort.
- Added constants and methods in ViewsBasicManager for pin settings.
- Added pin to top to Page content type
=> YSP-769: Add "Pin to Top" visual indicator

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml, web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Menu/CustomTaxonomyMenuLink.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.deploy.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/TaxonomyDisplayBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php
- Removed `field_audience` and `field_custom_vocab` blocks from layout builder design
- Set default `custom vocab` name after creation/import
- Add `Audience` and `Custom Vocab` menu items
- Update menu to match custom vocab name
- Revert to always sorting by pin to top in views
- Move `Vertical alignment` down in Spotlight block form
- Removed `wrapped callout text` for now (reintroduce after first release)
- Removed `taxonomy display` from two column sections
- Re-add `video` and `image banner` dials
- #880
- `Show current node` respects its set value on view edit
=> V1.13.0 Feedback/Bug Fixes

.github/workflows/release.yml, package.json
Reverts b382a15 since semantic-release can only run on `push` events and we cannot target the source branch, just the target.
Also, since semantic-release makes a commit to bump yalesites_profile version during release, add [skip ci] to the commit so that it does not trigger the release workflow a second time.
=> revert: release action can only run on push event, not pull_request

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/migrations/campus_groups_events.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Form/CampusGroupsSettings.php, web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Plugin/migrate/source/CampusGroupUrl.php, web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.info.yml
- **Add campus groups API key field to settings form**
- Added a new field `campus_groups_api_key` to the settings form.
- This field allows users to input Campus Groups Authentication Credentials.
- Updated the `submitForm` method to save the new API key field value.
- **Make module dependent on keys module**
- Updated the module to be dependent on the keys module.
- **Add headers and API key support for campus groups**
- Added `headers` configuration to `campus_groups_events.yml`.
- Updated `CampusGroupUrl.php` to include API key in headers.
- Implemented `getApiKeyFromKeysModule` to retrieve API key from keys module.
=> YSP-829: Hotfix: v1.13.0: Campus Groups API key support

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.tiles.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.tiles.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.tiles.field_enable_animation.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_enable_animation.yml
- Adds animation option to Tiles component
- Allows animation enabled state to be controlled by the tiles component. That state is passed to each tile-item.
- Atomic: https://github.com/yalesites-org/atomic/pull/306
- Component Library: https://github.com/yalesites-org/component-library-twig/pull/467
https://github.com/user-attachments/assets/fff06390-7461-4338-8aed-ed7e4f4b2cd7
=> IYY-303: Callout component animations and background image options

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
- Removes wrong function signature definition so that installs don't complain
=> Hotfix: v1130: Remove pass by reference on $display_id

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-event-meta-block.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.module
Work also done in [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/481)
- Hides "Add to Calendar" for Campus Group event sources
=> Hotfix: v1.13.0: Campus groups add to calendar fix

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.module, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-event-meta-block.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.module
- Removed direct use of RunMigrations controller.
- Updated ys_campus_groups_cron to use ys_campus_groups.manager service.
- Ensures better dependency injection and service management.
=> Hotfix: v1.13.0: Update cron to use service manager

README.md, web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
-  [IYY-351: Content Collection Bug: Book navigation theme setting is changing the grand hero overlay](https://fourkitchens.clickup.com/t/36718269/IYY-351)
- [IYY-358: Content Collection Bug: z-index issues](https://fourkitchens.clickup.com/t/36718269/IYY-358)
- [IYY-357: Content Collection Bug: Last item in the Content Collection nav is missing borders](https://fourkitchens.clickup.com/t/36718269/IYY-357)
- [IYY-362: Content Colection Bug: Header/ title spacing](https://fourkitchens.clickup.com/t/36718269/IYY-362)
- Updates selector for `book_navigation` setting.
- Resolve front-end issues related to content collection.
https://github.com/yalesites-org/component-library-twig/pull/486
=> IYY-351: Content Collection Bugs

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Gets the admin label from the plugin definition or falls back to the plugin ID and adds it as the default admin label value. This is applied to layout builder block add/update forms.
=> YSP-824 Admin Label automatically is the block name

web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
- Adds option to block: Floating Box Narrow 
Note that the "contained" option has a label of "Floating Box", so I added another with the key "contained-narrow" for which the label is "Floating Box Narrow"
PR for the component library is here: https://github.com/yalesites-org/component-library-twig/pull/492
=> YSP-716 :: Add "Contained Narrow" Design Option to Grand Hero Block

web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php, web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Work also done at:
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/485)
- Updated the `MetaFieldsManager` to use the last date in the array if no featured date is found.
- Changed the event featured date handling to use a specific variable instead of the first element of the dates array.
- Refactored event date sorting and added methods to improve code readability and maintainability.
- Added the `event_featured_date` to the event data and related components to ensure it is correctly handled and displayed.
- Passed `delta` of event date into render array to properly display date in views
- Modified event view to not be aggregated for multiple instances of the same node (with different dates) to occur
- Event card views do not generate the following …
=> YSP-844: Event Meta Block Date Visibility Improvements

web/profiles/custom/yalesites_profile/config/sync/cas.settings.yml
- Sets the "Custom Certificate Authority PEM Certificate" path so the CAS module does not need to autodiscover it, preventing authentication errors.
=> fix: specify path to CA PEM cert to prevent auth errors

web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml, web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
- Adds distinct filter to views_basic_scaffold to prevent duplicates
=> YSP-858 :: Taxonomy sub item filter shows multiple instances

composer.json, patches/robots.txt
Pager parameters are causing crawlers to index the same page multiple times, so this PR:
- Adds append logic to composer.json for robots.txt
- Adds `patches/robots.txt` for customizations that get appended to `web/robots.txt` by composer
- Disallows `/*?page=` parameters to prevent duplicate pages in search indexes
**Pantheon serves its own robots.txt for non-live environments, so this can only be tested locally:**
=> Disallow crawling of ?page= parameters

web/sites/ys.settings.local.php
When setting the CAS cert path in #933 to prevent auth errors in Pantheon environments, CAS logins broke under Lando. This PR overrides the CAS cert settings when running locally.
=> Fix CAS login under Lando

README.md, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/page-meta/layout--page-meta.html.twig
- A mock of the look and feel if we were to move the content collection above the title near the breadcrumbs
- Work done in:
=> YSP-892: Design treatment for active Content Collection parent menu items and location move

web/profiles/custom/yalesites_profile/composer.json
- Bumps ai_engine to 1.2.10 to incorporate accessibility fixes detailed in YSP-893
=> YSP-893: Bump AI Engine to v1.2.10

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.condensed.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.single.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.teaser.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_show_teaser_lead_in.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_show_social_media_sharing.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_show_social_media_sharing.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.deploy.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PostMetaBlock.php, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-post-meta-block.html.twig, web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
- Changes the setting for Social Media Links on Posts to be an opt-in instead of an opt-out
- Migrates `field_hide_sharing` to `field_show_social_media_sharing` for better naming
- Posts with none set will be set to `FALSE` (`0`)
- Posts with `field_hide_sharing` set to `FALSE` will have `field_show_social_media_sharing` set to `TRUE` (`1`)
- Posts with `field_hide_sharing` set to `TRUE` will have `field_show_social_media_sharing` set to `FALSE` (`0`)
- Modified [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/514) to handle these new changes
You can alternatively see each of these states in [Dave's test page](https://pr-971-yalesites-platform.pantheonsite.io/the-3-states-of-social-media-links)
=> YSP-912: Change default for social media sharing on Post content type

web/profiles/custom/yalesites_profile/config/sync/linkit.linkit_profile.default.yml
- Updated the metadata field in the linkit profile configuration to display the content type instead of the author. This improves the clarity of the metadata displayed for nodes.
=> YSP-927: Show Content Type in LinkIt module

web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml, web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Added dependencies and permissions for the wrapped_text_callout block content type across contributor, editor, platform_admin, and site_admin roles. This includes create, delete, edit, revert, and view permissions to ensure proper role-based access control.
Not noticeable change, but more for consistency with how we deal with permissions.
=> Add permissions for wrapped_text_callout content

web/profiles/custom/yalesites_profile/config/sync/ys_alert.settings.yml
- Changed the default 'status' value for alerts from active (1) to inactive (0) in ys_alert.settings.yml. This ensures alerts are not displayed by default until explicitly activated.
=> YSP-563: Turn off site alerts on starter kits

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.facts.field_text.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.facts_item.field_text.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
- Makes facts and figure block content field optional
- Converts facts and figure block's paragraph item content format from `heading_html` to `restricted_html`
- Add update hook to convert existing facts and figure paragraph items to utilize the new format
=> YSP-702: Facts and Figures: add links to items + make "content" optional

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
- Set the "required_fields" property for the "group_classifications" field to false in the event content type form display configuration, showing only one asterisk.
=> YSP-865: Event Content Type: "Basic info" has two 'required' asterisks

web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/two_column/layout--two-column.html.twig
- Refactored the two-column layout template to mimic the one column version.  This fixes drag and drop in that it provides the move url to use when dragging and dropping.
=> YSP-966: Drag and Drop is not saving

web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_content_ref.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/EntityReferenceSelection/CasAwareSelection.php
- Adds content type and CAS identifier to autocomplete for reference card entity references
- Enhances autocomplete display to show both the content type (e.g., "Page", "Post", "Event") and CAS protection status
- Provides visual indicators when content is CAS protected, helping users understand content will only be visible to logged-in users
- Improves user experience by making reference card selection more informative and transparent
=> YSP-938: Reference card page CAS protected not showing

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.callout.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.callout.default.yml, web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.cta_banner.default.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.callout.field_overlay_background_image.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_link.yml, web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_overlay_background_image.yml, web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_overlay_background_image.yml
- Adds `field_overlay_background_image` to the CTA Banner block content type
- Adds `field_overlay_background_image` to the Callout block content type  
- Updates form and view displays to include the new field for both block types
- Configures the field to reference media images using the media library
- Makes the `field_link` field optional for CTA Banner blocks (no longer required)
- Adjusts field weights for improved form layout on both content types
- Ensures proper dependencies and display settings for the new overlay background image field
- Other work completed in:
- [Atomic](https://github.com/yalesites-org/atomic/pull/367)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/529)
=> YSP-904: YPS: Add Image Background to Action Banner and Callout Blocks

web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
In working on #950, I noticed config_filter was dropped from config_split in [2.0.0](https://www.drupal.org/project/config_split/releases/2.0.0), but we've had it enabled all along. We will remove this module in a future release.
=> chore: disable unused config_filter module

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Previously, the block plugin admin label was always set as the default value for the layout builder block label. This caused existing labels to be overwritten unintentionally. Now, the default admin label is only set if the current label value is empty, preserving user input.
- Adds conditional around setting to only apply if the field is empty
=> YSP-1072: Admin label change to stop overriding on 'configure'

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.action.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Hide add user action and user menu items for non-platform_admins
- Disable caching for admin items on the user list page to avoid caching between users issues
=> YSP-920 :: Clean Up User Addition Experience for Non-Platform Admins 

web/profiles/custom/yalesites_profile/composer.json, web/themes/custom/ys_admin_theme/css/admin-ui.css, web/themes/custom/ys_admin_theme/css/admin-ui.css.map, web/themes/custom/ys_admin_theme/scss/admin-ui.scss
- Enhance the visibility and accessibility of error states for checkboxes and labels in Gin dark mode.
- Other work completed in https://github.com/yalesites-org/atomic/pull/382
=> Accessibility RC fixes

web/profiles/custom/yalesites_profile/modules/custom/ys_book/src/YsExpandBookManager.php
- Ensure siblings in the book tree are sorted by their weights and localized titles for consistent ordering.
And thanks @vinmassaro for finding the place this issue was happening!!!!
=> Hotfix: Sort tree siblings by weight and title

web/profiles/custom/yalesites_profile/composer.json, web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/EventSubscriber/ExternalSourceRedirectSubscriber.php, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
- Reload node entity and add aggressive cache prevention headers in `ExternalSourceRedirectSubscriber` to ensure external source redirects use the latest field data.
- Add `ys_core_node_update()` to invalidate caches when `field_external_source` is updated, preventing stale redirects due to entity or page cache.
- Fix service injection for route match.
Note:  We can still visit the idea of using the FieldRedirection module, but as this is being seen in current sites, this is a quicker response.
=> YSP-860: Cache not cleared when updating external link in Post

web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_taxonomy_manager/ys_taxonomy_manager.routing.yml
- Fix permission on ys_taxonomy_manger to use the same permission as the parent module, give access to site admin
[Login and then go here](https://pr-1050-yalesites-platform.pantheonsite.io/admin/structure/taxonomy_manager/voc)
=> YSP-1094 :: Fix Taxonomy Manager access

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
- Auto-detects if an image is portrait or landscape
- Portrait images are rendered using `Content Spotlight Portrait` responsive image style
=> Event Teaser Image: Allow portait images

pantheon.upstream.yml, web/profiles/custom/yalesites_profile/composer.json, web/sites/default/settings.php, web/sites/default/settings.redis.php
Some sites will require Redis Object Cache for better performance. This PR:
- Adds `drupal/redis` module
- Conditionally loads the redis configuration file if running on Pantheon and Redis service is enabled
- Excludes Redis module from config tracking so it can be enabled on individual sites without being reverted by config
> [!NOTE]
>  Since lando also sets these same environment vars and spins up redis as part of the pantheon recipe, local environments will also use redis and see better performance.
=> Add Redis support

web/profiles/custom/yalesites_profile/config/sync/field.field.node.resource.field_media.yml
- The 'Resource Media' field on the resource content type is now required.
=> RC: Make resource media field required

web/profiles/custom/yalesites_profile/config/sync/imagemagick.settings.yml, web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
- Ensure PNG transparency is retained during all image style operations by adding ImageMagick arguments for alpha channel and RGBA support.
- Also optimize PNG compression and exclude unnecessary chunks.
- Update config to apply these arguments globally for ImageMagick v6.
- Other work completed in https://github.com/yalesites-org/component-library-twig/pull/576
=> YSP-926: Views: Card grid stroke outline

web/sites/default/settings.php
- Adds version number display to environment indicators for development, test, and live environments
- Updates environment indicator names to include profile version (e.g., "Development - 2.9.0")
- Implements dynamic version parsing from yalesites_profile.info.yml file
=> YSP-1135:  Environment Indicators: User found the messaging to be misleading

web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/MicrosoftForm.php
- Adds support for forms.cloud.microsoft URLs in addition to existing forms.office.com URLs
- Updates regex pattern to capture both URL structures (office.com with query params and cloud.microsoft with path-based form IDs)
- Implements secure URL reconstruction following patterns used by other embed sources (GoogleMaps, Qualtrics)
- Adds minimal sanitization that prevents injection attacks while preserving Microsoft's actual URL parameters
- Fixes getUrl() method logic to properly detect and handle both URL formats based on captured parameters
- Replaces overly restrictive parameter filtering with minimal sanitization approach to support unknown Microsoft URL variations
=> YSP-1165: Support new MS Forms source
