yalesites-org/yalesites-project

.github/BUILD_TOOLS.md
composer.json
package.json
scripts/node/build-theme.sh
scripts/node/build.sh
scripts/node/confex.sh
scripts/node/confim.sh
scripts/node/export-db.sh
scripts/node/get-assets.sh
scripts/node/get-db.sh
scripts/node/get-files.sh
scripts/node/import-data.sh
scripts/node/lint.sh
scripts/node/rebuild.sh
scripts/node/theme.sh

- Provides `package.json` file with scripts that now live in `scripts/node` to help development process
Theme related docs and scripts are not accurate/functional. We can refactor those later when we have this narrowed down.

YALB-257: Add local development scripts

---

web/profiles/custom/yalesites_profile/composer.json

- Adds functionality bullet item
- Fixes this or that bullet item

YALB-428: Update layout_paragraphs to v2

---

web/profiles/custom/yalesites_profile/composer.json
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.accordion.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.accordion_item.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.embed.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.image.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pop_out_image.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pull_quote.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.heading_html.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.image.field_text.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.heading_html.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
web/profiles/custom/yalesites_profile/config/sync/user.role.authenticated.yml

- Configures text formats
- Updates wysiwyg filters and settings for all paragraph types

YALB-447: Configure text formats

---

.circleci/config.yml
pantheon.upstream.yml

YALB-558: CI Fixes

---

.ci/build/php
.ci/deploy/pantheon/dev-multidev
.circleci/config.yml
composer.json

- Adds functionality bullet item
- Fixes this or that bullet item

ci(YALB-558): reset ci

---

web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.plain_text.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.media_library.yml

- Review formats and filters.
- Add basic text styling to 'Basic HTML' and remove quotes.
- Add paste and indent tools to WYSIWYG.

YALB-538: Update text formats

---

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tab.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tabs.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.tab.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.tabs.default.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.heading_html.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tab.field_content.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tab.field_heading.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tabs.field_tab.yml
web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_tab.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.tab.yml
web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.tabs.yml

- Creates a tabs paragraph type that can be added to a page.

YALB-438: creates tabs paragraph

---

composer.json

- Applies a patch (that I created) to the layout_paragraphs module to improve the editing experience
I submitted the change to the module here https://www.drupal.org/project/layout_paragraphs/issues/3280171. Any reviews, etc. would be great!

YALB-537: Layout Paragraphs - Polish frontend editing/saving experience

---

web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.callout.field_style_color.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_color.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_position.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.pull_quote.field_style_variation.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_style_variation.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_position.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_variation.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_width.yml

- Requires style variations per component

YALB-726: Make style variations per component required

---

web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/layout-paragraphs.css
web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.libraries.yml

**This PR requires work in the atomic theme here: https://github.com/yalesites-org/atomic/pull/45**
- Creates css for all themes to fix a lpb issue

YALB-742: Update action banner

---

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.media_library.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.video.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.media_library.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.video.default.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.media.video.field_media_oembed_video.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.video.field_heading.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.video.field_text.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.video.field_video.yml
web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_media_oembed_video.yml
web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_video.yml
web/profiles/custom/yalesites_profile/config/sync/media.type.video.yml
web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.video.yml

- creates video paragraph and media type

YALB-712 create video paragraph

---

web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.gallery_item.gallery_modal_content.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.gallery_item.gallery_modal_media.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.paragraph.gallery_modal_content.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.paragraph.gallery_modal_media.yml

**Needs the related Atomic and CL PRs.**
- Creates view modes for Gallery items

YALB-745: Wire gallery paragraphs

---

web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.accordion.field_heading.yml

- Update the accordion heading field label from "Heading" to "Accordion Component Heading"
No functional changes. Reviewing the YML should be good enough.

YALB-825: Update accordion label

---

docs/setup.md

- Added section for GitHub and setting up SSH key, which people will need to do if they're on a new machine

YALB-923: Improve readme for project onboarding

---

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.grand_hero.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pull_quote.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.wrapped_image.default.yml
web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_text.yml
web/profiles/custom/yalesites_profile/config/sync/ys_alert.settings.yml

- Change paragraph 'Styles' labels to 'Design Options'

YALB-917: Update form labels

---

web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml

- YALB-978: update labels for component styles
- YALB-982: rename settings admin menu link
- YALB-1007: new label for local tasks flyout

YALB-987: Clear and consistant UI epic

---

web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_media_file.yml

- Adds the ability to upload xlsx files.

YALB-1209: Allows xlsx files to be uploaded

---

web/private/scripts/confim.php

- Update confim.php quicksilver script when not run by the CI user

YALB-1102: Add CI jobs for releases

---

web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml

- Adds functionality bullet item
- Fixes this or that bullet item

YALB-1262: Ignore levers on config import

---

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php

- Additional checks to resolve warnings in log files

Views basic fixes - branched from master

---

docs/setup.md
web/profiles/custom/yalesites_profile/modules/custom/ys_alert/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_themes/README.md

For more senior developers, this allows an at a glance look on the requirements to have set up, while allowing a deeper dive into the document to find specifics.
- Adds documentation geared toward a more mid/senior level developer
- Keep existing documentation in tact so that questions regarding higher level explanation can be answered by digging deeper
[Branch markdown file with the setup information](https://github.com/yalesites-org/yalesites-project/blob/YALB-1512-setup-docs/docs/setup.md)

YALB-1512: Docs: Verify and update developer setup documentation

---

web/profiles/custom/yalesites_profile/modules/custom/ys_alert/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_core/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_mail/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_themes/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/README.md
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/README.md

- Creates or updates all module readme files in the YaleSites profile.
- Readme files should describe the purpose of the module and give some sense of the work it encapsulates.
- None. This is a non-functional change. Just review the updated files for their content.

YALB-1204: Update all custom module readme files

---

docs/development.md

- Updates the development.md file to includes helpful notes and best practices on contributing to the YaleSites data model.
- This is a documentation PR. There are no functional changes to the code. Please review the documentation for clarity and completeness.

YALB-1155: Add data model best practices do developer Readme file

---

web/profiles/custom/yalesites_profile/composer.json

- Updates pathauto to 1.12 for PHP 8.2 compatibility

Hotfix: update pathauto to 1.12 for PHP 8.2 compatibility 

---

web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.advanced.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.all_blocks.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.basic.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.media.yml

- Some config needed to be re-exported after updating to D10, otherwise `config:import` always has pending changes.

Export config post-D10

---

.ci/github/create_release_pull_request
.github/workflows/release_pr.yml

- Adds an action to create a release pull request

feat: add action workflow for release pull request

---

.ci/github/create_release_pull_request
.github/workflows/release_pr.yml

- Adds automatic updating of release PR description when new changes are committed to `develop`

Actions: update existing release PRs

---

.ci/github/create_release_pull_request

- Fixes `jq` errors when updating existing release PRs

fix: update existing release PRs correctly without errors

---

.ci/github/create_release_pull_request

- In the actions workflow to create/update a release PR, properly filter merge commits so they do not appear in the list or as null.

fix: update jq condition to properly filter merge commits from diff

---

web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install

- https://github.com/yalesites-org/yalesites-project/pull/544

fix: YALB(1963): Hotfix: Text Style Variation not set on existing blocks

---

.ci/github/deploy_release_sites

- Push code before creating multidev
- Increase `terminus workflow:wait` to 600s

Github Actions: minor changes pull request creation

---

.github/workflows/release_pr.yml

- Sets persistent Github Actions key for release_pr job.

Github Actions: set persistent variable name for release_pr cache

---

.github/workflows/build_deploy_and_test.yml
.github/workflows/release.yml

- Updates all actions to latest v4 to remove node deprecation warnings
- Sets node version to 20 for release creation

Update actions to latest versions 

---

web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Form/AlertSettings.php
web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php
web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/YaleSitesMediaManager.php
web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceBase.php
web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceManager.php
web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/Field/FieldFormatter/EmbedDefaultFormatter.php
web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/Field/FieldWidget/EmbedDefaultWidget.php
web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/media/Source/Embed.php
web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileContactBlock.php
web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php
web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php

- Fix code issues found after the analyzer was updated

chore(fix-phpcs): auto-fix new phpcs analyzer findings

---

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php

- Adds offset field to viewsDefaultWidget
- Also fixes an error "undefined array key operator"

YSP-548 Views: Offset results

---

web/profiles/custom/yalesites_profile/composer.json

feat(v140): update atomic to 1.33.0

---

web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesSearchFormBlock.php

- Fix search form caching issue.

JAKALA: Fix search form caching issue.

---

web/profiles/custom/yalesites_profile/config/sync/ai_engine_chat.settings.yml
web/profiles/custom/yalesites_profile/config/sync/ai_engine_metadata.settings.yml
web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
web/profiles/custom/yalesites_profile/config/sync/core.extension.yml

- 0f5abbd5035bc6aa4fe15a0ecd12baaa3b1c6545
- f5467c6e9fa1ea6b2cc096a69acdc925b58b4d3d

Hotfix: YSP-632: AI: AI modules disabled on release

---

web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php

- 06d02ebe346faebfc6a7feda218e7686602a2537
- b3f3a0826d2cd962a6cb8ba7509b14db4e086be6
- 0faa0fb0aac490076e9a8d7a4b687d5ffb45b904

Hotfix v1.8.0: Default show_thumbnail to true for existing views

---

web/profiles/custom/yalesites_profile/composer.json

- Updates [atomic](https://github.com/yalesites-org/atomic) to 1.39.0

feat: update atomic to 1.39.0

---

package.json

- Updates semantic-release to fix secondary rate limit issue during releases

feat: update semantic-release to ^24

---

web/profiles/custom/yalesites_profile/config/sync/editor.editor.webform_default.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.heading_html.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.plain_text.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
web/profiles/custom/yalesites_profile/config/sync/filter.format.webform_default.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.advanced.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.all_blocks.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.basic.yml
web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.media.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.archive.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.block_content.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.editoria11y_dismissals.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.editoria11y_results.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.export_media.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.export_nodes.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.export_taxonomy.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.files.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.frontpage.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.glossary.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.media.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.media_library.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.moderated_content.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.redirect.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.redirect_404.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.section_library.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.taxonomy_lookup.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.user_admin_people.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.watchdog.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.webform_submissions.yml

- Export config again for remaining changes needed by #792

chore: last config export for drupal 10.3 upgrade

---

composer.json

- Update Drupal core to [10.3.10](https://www.drupal.org/project/drupal/releases/10.3.10)

Update drupal core to 10.3.10

---

web/profiles/custom/yalesites_profile/composer.json

- Patch updated in https://www.drupal.org/project/focal_point/issues/2830678 now only applies to focal_point 2.1.2

fix: update focal_point to 2.1.2 so patch #2830678 still applies

---

.ci/deploy/pantheon/dev-multidev

Reverts dev-multidev changes from #841.

fix: restore step order in dev-multidev script from #841

---

web/profiles/custom/yalesites_profile/composer.json

Update atomic to 1.40.0

---

web/profiles/custom/yalesites_profile/composer.json
web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.custom_vocab.default.yml
web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.custom_vocab.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php

- Pinned events now show first
- Updated to use newest CL/atomic release

v1.13.0 Feedback Fixes 2

---

web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/migrations/campus_groups_events.yml

- Update campus groups migration to move ticket_cost data to registration URL
- Remove CTA from campus groups integration (instead using registration URL)

v1.13.x Feedback Fixes 3

---

web/profiles/custom/yalesites_profile/composer.json

Bump atomic to 1.21.0

---

web/profiles/custom/yalesites_profile/composer.json

Update atomic to 1.45.0

---

README.md

- See work done in https://github.com/yalesites-org/component-library-twig/pull/502

YSP-874: Quote Block 'Bar Right' Style Alignment Issues in Narrow Sections

---

composer.json
web/profiles/custom/yalesites_profile/composer.json

- Updates to drupal/core:10.3.14
- Updates to drupal/config_split:2.0.2 (security release)

Update to drupal/core:10.3.14

---

web/profiles/custom/yalesites_profile/composer.json

Update Atomic to v1.46.0

---

web/profiles/custom/yalesites_profile/composer.json
web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/README.md

- Guards against `#block` existence
- Add sample D7 settings for migration assistance
- Work also done in [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/520) and [Atomic](https://github.com/yalesites-org/atomic/pull/359)
- Bump Atomic to hotfix release version

Hotfix: YSP-943/YSP-945: Grand Hero and Table fixes

---

web/profiles/custom/yalesites_profile/composer.json

Update atomic to 1.51.0

---

web/profiles/custom/yalesites_profile/composer.json

Bump atomic to 1.52.0

---

web/profiles/custom/yalesites_profile/composer.json

Bump atomic to 1.53.0

---

web/profiles/custom/yalesites_profile/composer.json

Update atomic to 1.57.0

---

web/profiles/custom/yalesites_profile/modules/custom/ys_ai/ys_ai.info.yml

- Adding `ys_ai` dependency fix to `develop` branch so new local builds can complete

Backport ys_ai fix to develop branch

---

web/profiles/custom/yalesites_profile/composer.json

Bump Atomic to 1.62.0

---

web/profiles/custom/yalesites_profile/composer.json

Update atomic to 1.63.0
